[package]
name = "yoctui-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
libc.workspace = true

[dev-dependencies]
ratatui.workspace = true
yoctui-app = { version = "0.1.10", path = "../yoctui-app" }
yoctui-model = { version = "0.1.10", path = "../yoctui-model" }
yoctui-ui = { version = "0.1.10", path = "../yoctui-ui" }
