//! Regression tests grouped around devwork_editor_detects_languages_and_supports_search_undo_and_redo.
use super::*;

mod primary_contract;

mod clean_state_requires_confirmation_before_starting;
mod devwork_editor_reports_structural_diagnostics_without_claiming_compiler_authority;
mod layer_selection_stays_in_workspace_bounds;
mod layer_tree_loads_children_lazily_and_collapses_without_losing_parent;
mod selected_layer_opens_its_directory;
mod selected_layer_opens_the_in_tui_workspace_editor;

mod layer_tree_hidden_filter_and_search_keep_selection_bounded;
mod ux_list_tree_layer_flatten_rejects_cycles_and_hard_bounds_depth;

mod config_source_opens_single_typed_relative_operation;
mod configuration_selection_stays_in_workspace_bounds;
mod layer_file_right_focuses_preview_and_arrows_scroll_only_the_preview;
mod layer_tree_external_editor_effect_is_typed_and_missing_selection_is_visible;
mod layer_tree_ignores_stale_preview_and_tracks_binary_metadata;

mod config_source_picker_uses_typed_operation_line_and_restores_focus;

mod config_source_rejects_escape_and_explains_unloaded_detail;
mod metadata_search_tracks_query_and_resets_metadata_selection;

mod build_target_editor_requires_confirmation_before_starting;
mod image_picker_selects_an_image_then_requires_build_confirmation;
mod log_match_navigation_stays_within_active_search_results;
mod search_clear_actions_reset_every_typed_query_without_closing_focus;

mod theme_picker_applies_named_selection_immediately_and_persists_on_accept;

mod theme_picker_respects_no_color_launch_override;

mod bounded_telemetry_history_retains_only_the_latest_valid_samples;
mod build_completion_stays_open_until_dismissed;
mod build_options_prefill_the_current_target_and_requested_task;
mod theme_picker_restores_original_theme_when_closed_with_escape;

mod coexistence_diagnostic_parses_parallelism_without_mutating_workspace;
