//! Regression tests grouped around coexistence_diagnostic_distinguishes_nominal_busy_and_unknown.
use super::*;

mod primary_contract;

mod parallel_make_parser_rejects_unbounded_or_dynamic_job_counts;

mod animation_ticks_advance_unless_reduced_motion_is_enabled;
mod bbmask_editing_requires_a_preview_and_confirmation;
mod build_task_scrolling_stays_within_observed_task_history;
mod duplicate_or_unknown_completion_does_not_increment_task_count;
mod hardening_stress_model_retention_preserves_high_volume_invariants;
mod log_filters_combine_severity_recipe_task_and_search;
mod paused_log_view_holds_the_visible_horizon;
mod quitting_always_requires_confirmation;
mod settings_persistence_failure_retains_the_preview_and_dirty_state;
mod settings_selection_and_changes_are_typed_and_persisted;
mod telemetry_provenance_catalog_is_complete_and_honest;
mod toggles_log_view_preferences;
mod typed_event_actions_update_metadata_and_preserve_unknown_progress;

mod cycles_log_severity_filter;
mod log_retention_prefers_important_diagnostics_and_reports_coalescing;
mod log_state_reports_bounded_vertical_and_horizontal_positions;
mod scrolling_logs_pauses_follow_and_bounds_offset;

mod log_batches_preserve_critical_order_counts_and_cached_search;

mod log_build_filter_selection_source_and_copy_are_typed;
mod ux_logs_virtualized_window_and_source_time_filters_stay_bounded;

mod ux_logs_bookmarks_survive_preferred_eviction_and_support_correlated_jumps;

mod ux_logs_tasks_errors_and_job_history_open_exact_correlated_records;

mod log_terminal_diagnostics_are_protected_and_observable;
mod request_validation;
mod ux_logs_copy_and_filtered_export_are_unicode_safe_and_hard_bounded;
