//! Regression tests grouped around ux_dependency_graph_normalization_reports_hard_bounds.
use super::*;

mod devtool_modify_editor_loads_saves_and_builds_selected_recipe;
mod devtool_publish_finish_requires_clean_status_and_configured_layer_confirmation;
mod devtool_publish_update_requires_authoritative_workspace_and_confirmation;
mod devtool_target_deploy_requires_authoritative_workspace_and_validated_confirmation;
mod devtool_target_reset_requires_authoritative_removable_source_and_confirmation;
mod devtool_undeploy_and_upgrade_use_distinct_validated_confirmations;
mod signature_model_derives_deterministic_typed_differences;
mod signature_model_reducer_correlates_states_selection_and_comparison;
mod signature_model_validates_normalizes_duplicates_and_bounds;
mod ux_dependency_graph_normalization_reports_hard_bounds;
mod ux_dependency_graph_projection_bounds_cycles_filters_reverse_and_collapse;
mod ux_dependency_graph_reducer_owns_filter_reverse_expansion_and_exact_selection;
mod ux_dependency_graph_routes_only_typed_identity_provider_and_task_log;

mod external_recipe_edit_keeps_diff_and_allows_ctrl_b_build;
