//! Regression tests grouped around live_tasks_reducer_keeps_honest_counts_filters_and_bounded_selection.
use super::*;

mod primary_contract;

mod task_state_distinguishes_identified_queue_entries_from_aggregate_waiting_work;

mod live_tasks_filter_supports_recipe_task_worker_and_duration;

mod task_rows_preserve_authoritative_optional_fields_without_derivation;
mod task_rows_prioritize_running_waiting_and_terminal_states;

mod build_summary_uses_typed_counts_and_freezes_terminal_elapsed_time;

mod recipe_navigation_uses_authoritative_provider_logs_and_local_patches;

mod recipe_navigation_explains_missing_and_remote_only_paths;

mod recipe_qa_action_requires_authoritative_tasks_and_exact_confirmation;

mod recipe_qa_action_reducer_retains_output_and_honest_empty_artifacts;

mod config_metadata_keeps_global_and_recipe_scopes_typed_and_independent;

mod devtool_metadata_uses_absolute_identity_and_ignores_other_recipe_status;

mod devtool_metadata_rejects_missing_or_relative_provider_identity;

mod config_workspace_lazy_detail_is_identity_correlated_and_search_bounded;

mod config_workspace_refresh_preserves_selected_variable_identity;

mod config_copy_uses_only_loaded_detail_for_the_exact_identity;

mod config_copy_explains_loading_failure_and_absent_unexpanded_value;

mod config_scope_keeps_global_and_recipe_detail_independent;

mod config_scope_falls_back_to_global_when_recipe_disappears;

mod config_compare_reports_equal_different_and_unavailable_fields;
