//! Regression tests grouped around completed_builds_are_retained_in_session_history.
use super::*;

mod error_completion_outcomes_are_distinct_and_actionable;
mod error_entries_gain_typed_category_summary_metadata_and_suggestions;
mod primary_contract;
mod recipe_bitbake_action_uses_authoritative_tasks_picker_and_confirmation;
mod recipe_metadata_refresh_is_typed_and_replaces_stale_detail;
mod recipe_selection_stays_in_workspace_bounds;
mod recipes_workspace_filter_selection_refresh_and_failure_are_identity_stable;
mod selected_error_jumps_to_exact_log_without_replacing_user_filters;
mod selected_error_opens_its_source_path;

mod devtool_modify_requires_authoritative_status_and_confirmation;
mod firmware_menuconfig_uses_detected_provider_and_requires_reported_task;
mod kernel_menuconfig_uses_virtual_provider_and_requires_reported_task;
mod recipe_bitbake_action_rejects_unavailable_and_malformed_tasks;
mod selected_recipe_build_requires_confirmation;
mod selected_recipe_clean_prefills_the_clean_task;
mod selected_recipe_menuconfig_opens_the_embedded_terminal_chooser;
mod selected_recipe_requests_authoritative_dependencies;
mod ux_dependency_graph_finds_deterministic_bounded_paths_through_cycles;
mod ux_dependency_graph_normalizes_nodes_edges_and_reverse_lookup;
mod ux_dependency_graph_reducer_preserves_identity_and_explicit_states;
