use crate::DevtoolUtilityCommand;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommandId {
    BuildImage,
    SelectImage,
    BuildSelectedRecipe,
    EditBbmask,
    OpenDashboard,
    OpenInsights,
    OpenBuildHistory,
    OpenSignatures,
    OpenLayerRelationships,
    OpenDevtoolWorkspace,
    OpenKernel,
    OpenFirmware,
    OpenBbmask,
    OpenCommandPalette,
    Quit,
    OpenLayers,
    OpenRecipes,
    OpenPackages,
    OpenImages,
    OpenHardware,
    OpenSdk,
    OpenDependencies,
    OpenTesting,
    OpenSecurity,
    OpenQa,
    OpenTasks,
    OpenLogs,
    OpenErrors,
    OpenConfiguration,
    OpenRawMode,
    OpenTerminalSessions,
    OpenGitUi,
    OpenDevtool(DevtoolUtilityCommand),
    OpenBitBakeConfigBuild,
    OpenBitBakeLayersShowLayers,
    OpenBitBakeLayersShowRecipes,
    OpenBitBakeLayersShowOverlayed,
    OpenBitBakeLayersShowAppends,
    OpenBitBakeLayersShowCrossDepends,
    OpenBitBakeLayersAddLayer,
    OpenBitBakeLayersRemoveLayer,
    OpenBitBakeLayersFlatten,
    OpenBitBakeLayersLayerIndexFetch,
    OpenBitBakeLayersLayerIndexShowDepends,
    OpenBitBakeLayersCreateLayer,
    OpenBitBakeLayersShowMachines,
    OpenBitBakeLayersSaveBuildConf,
    OpenBitBakeLayersCreateLayersSetup,
    OpenMaintenance,
    OpenBuildEnvironment,
    OpenCompatibility,
    OpenSettings,
    ChooseTheme,
    FocusNavigator,
    FocusWorkspace,
    FocusInspector,
    PreviousSubfocus,
    NextSubfocus,
    TogglePaneZoom,
    ToggleInspector,
    ScrollFirst,
    ScrollLast,
    OpenOnboarding,
    OpenHelp,
    OpenAbout,
}

impl CommandId {
    /// Inspect a navigation route without constructing dialogs or executing it.
    pub const fn screen(self) -> Option<crate::Screen> {
        Some(match self {
            Self::OpenDashboard => crate::Screen::Dashboard,
            Self::OpenInsights => crate::Screen::Insights,
            Self::OpenBuildHistory => crate::Screen::BuildHistory,
            Self::OpenSignatures => crate::Screen::Signatures,
            Self::OpenLayerRelationships => crate::Screen::LayerRelationships,
            Self::OpenDevtoolWorkspace => crate::Screen::Devtool,
            Self::OpenKernel => crate::Screen::Kernel,
            Self::OpenFirmware => crate::Screen::Firmware,
            Self::OpenBbmask => crate::Screen::Bbmask,
            Self::OpenLayers => crate::Screen::Layers,
            Self::OpenRecipes => crate::Screen::Recipes,
            Self::OpenPackages => crate::Screen::Packages,
            Self::OpenImages => crate::Screen::Images,
            Self::OpenHardware => crate::Screen::Hardware,
            Self::OpenSdk => crate::Screen::Sdk,
            Self::OpenDependencies => crate::Screen::Dependencies,
            Self::OpenTesting => crate::Screen::Testing,
            Self::OpenSecurity => crate::Screen::Security,
            Self::OpenQa => crate::Screen::Qa,
            Self::OpenTasks => crate::Screen::Tasks,
            Self::OpenLogs => crate::Screen::Logs,
            Self::OpenErrors => crate::Screen::Errors,
            Self::OpenConfiguration => crate::Screen::Configuration,
            Self::OpenRawMode => crate::Screen::RawMode,
            Self::OpenTerminalSessions => crate::Screen::TerminalSessions,
            Self::OpenMaintenance => crate::Screen::Maintenance,
            Self::OpenBuildEnvironment => crate::Screen::BuildEnvironment,
            Self::OpenCompatibility => crate::Screen::Compatibility,
            Self::OpenSettings => crate::Screen::Settings,
            Self::OpenHelp | Self::OpenAbout => crate::Screen::Help,
            _ => return None,
        })
    }
}
