//! Regression tests grouped around snapshot_timing_observed_reducer_does_not_fall_back_to_local_clock.
use super::*;

mod primary_contract;

mod render_cache_viewport_recomputes_without_stale_selection_state;

mod background_job_completes_and_survives_workspace_navigation;
mod background_job_history_pins_active_rows_and_bounds_shared_selection;
mod background_job_records_failure_and_loss;
mod function_shortcut_catalog_is_complete_unique_and_truthful;
mod notification_transient_status_uses_typed_priority_and_dismisses;

mod background_job_summary_counts_exact_states_and_current_daemon_ownership;

mod job_history_deduplicates_only_matching_terminal_daemon_builds;

mod inspector_mode_tracks_typed_screen_selection_and_navigator_focus;

mod background_job_cancellation_requires_capability_and_acknowledgement;
mod background_job_history_and_output_retention_are_bounded_and_observable;
mod background_job_invalid_transitions_leave_state_unchanged;
mod background_job_rejected_cancellation_returns_to_running;
mod bounded_logs_report_eviction;
mod navigator_selection_and_focus_cycle_are_bounded;
mod task_inspector_projects_recipe_dependencies_and_a_bounded_correlated_tail;

mod navigator_screen_projects_the_bounded_selection;
