def render_parameter(parameter: Parameter) -> str:
    return (
        "RawParameter { "
        f"id: RawParameterId::new({quoted(parameter.id)}).unwrap(), "
        f"label: {quoted(parameter.label)}.into(), "
        f"placeholder: {quoted(parameter.placeholder)}.into(), "
        f"kind: RawParameterKind::{parameter.kind}, "
        "presence: RawParameterPresence::Required }"
    )


def render_command(entry: Entry) -> str:
    command_id = f"{entry.category_id}.l{entry.line:04d}"
    reference_id = f"wrynose-6-0.l{entry.line:04d}"
    common = f"""        RawCommand {{
            id: RawCommandId::new({quoted(command_id)}).unwrap(),
            category: RawCategoryId::new({quoted(entry.category_id)}).unwrap(),
            label: {quoted(entry.command)}.into(),
            description: {quoted(entry.description)}.into(),
            reference: RawReference {{
                id: RawReferenceId::new({quoted(reference_id)}).unwrap(),
                heading: {quoted(entry.heading)}.into(),
                command: {quoted(entry.command)}.into(),
                description: {quoted(entry.description)}.into(),
            }},
"""
    if not entry.executable:
        kind = "ShellPipeline" if entry.command.startswith("bitbake ") else "CompanionTool"
        reason = (
            "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
            if kind == "ShellPipeline"
            else "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv."
        )
        return (
            common
            + "            parameters: vec![],\n"
            + "            execution: RawExecutionPolicy::ReferenceOnly {\n"
            + f"                kind: RawReferenceKind::{kind},\n"
            + f"                reason: {quoted(reason)}.into(),\n"
            + "            },\n"
            + "        },\n"
        )

    parameters, arguments = command_parts(entry.command)
    capability_names = capabilities(entry.command)
    capability_rows = ", ".join(f"CapabilityId::{name}" for name in capability_names)
    parameters_text = ",\n                ".join(render_parameter(item) for item in parameters)
    arguments_text = ",\n                    ".join(arguments)
    return (
        common
        + "            parameters: vec![\n"
        + (f"                {parameters_text}\n" if parameters else "")
        + "            ],\n"
        + "            execution: RawExecutionPolicy::Executable {\n"
        + "                template: RawExecutableTemplate {\n"
        + "                    executable: RawExecutable::BitBake,\n"
        + "                    arguments: vec![\n"
        + (f"                    {arguments_text}\n" if arguments else "")
        + "                    ],\n"
        + "                    capabilities: RawCapabilityRequirement::All {\n"
        + f"                        capabilities: vec![{capability_rows}],\n"
        + "                    },\n"
        + f"                    interaction: RawInteractionMode::{interaction(entry.command)},\n"
        + f"                    safety: RawSafetyClass::{safety(entry.command, capability_names)},\n"
        + "                },\n"
        + "            },\n"
        + "        },\n"
    )


def generate() -> str:
    categories, entries = read_reference()
    executable_count = sum(entry.executable for entry in entries)
    category_rows = "".join(
        f"""        RawCategory {{
            id: RawCategoryId::new({quoted(category.id)}).unwrap(),
            label: {quoted(category.label)}.into(),
            reference_heading: {quoted(category.heading)}.into(),
            kind: RawCategoryKind::{category_kind(category)},
        }},
"""
        for category in categories
    )
    command_rows = "".join(render_command(entry) for entry in entries)
    generated = f"""// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub const RAW_REFERENCE_SHA256: &str = {quoted(EXPECTED_SHA256)};
pub const RAW_BUILTIN_CATEGORY_COUNT: usize = {len(categories)};
pub const RAW_BUILTIN_COMMAND_COUNT: usize = {len(entries)};
pub const RAW_BUILTIN_EXECUTABLE_COUNT: usize = {executable_count};

impl RawCatalog {{
    pub fn builtin() -> Self {{
        Self {{
            version: RAW_CATALOG_VERSION,
            categories: vec![
{category_rows}            ],
            commands: vec![
{command_rows}            ],
        }}
    }}
}}

#[cfg(test)]
mod raw_catalog_tests {{
    use super::*;

    fn command(line: usize) -> RawCommand {{
        RawCatalog::builtin()
            .commands
            .into_iter()
            .find(|command| command.reference.id.as_str() == format!("wrynose-6-0.l{{line:04}}"))
            .unwrap()
    }}

    #[test]
    fn raw_catalog_builtin_is_complete_bounded_and_valid() {{
        let catalog = RawCatalog::builtin();
        catalog.validate().unwrap();
        assert_eq!(catalog.categories.len(), RAW_BUILTIN_CATEGORY_COUNT);
        assert_eq!(catalog.commands.len(), RAW_BUILTIN_COMMAND_COUNT);
        assert_eq!(
            catalog.commands.iter().filter(|command| matches!(command.execution, RawExecutionPolicy::Executable {{ .. }})).count(),
            RAW_BUILTIN_EXECUTABLE_COUNT
        );
    }}

    #[test]
    fn raw_catalog_preserves_exact_help_and_structured_templates() {{
        let task = command(167);
        assert_eq!(task.description, "Execute one named task for a recipe.");
        let RawExecutionPolicy::Executable {{ template }} = task.execution else {{ panic!("task command must execute") }};
        assert_eq!(template.display_template(&task.parameters).as_deref(), Some("bitbake -c <task> <recipe>"));

        let joined = command(145);
        let RawExecutionPolicy::Executable {{ template }} = joined.execution else {{ panic!("UI command must execute") }};
        assert!(matches!(template.arguments[0], RawArgument::JoinedParameter {{ .. }}));

        let composed = command(87);
        let RawExecutionPolicy::Executable {{ template }} = composed.execution else {{ panic!("task syntax must execute") }};
        assert!(matches!(template.arguments[0], RawArgument::Composed {{ .. }}));
    }}

    #[test]
    fn raw_catalog_marks_interactive_destructive_empty_and_reference_only_entries() {{
        let devshell = command(607);
        let RawExecutionPolicy::Executable {{ template }} = devshell.execution else {{ panic!("devshell must execute") }};
        assert_eq!(template.interaction, RawInteractionMode::InteractivePty);

        let cleanall = command(593);
        let RawExecutionPolicy::Executable {{ template }} = cleanall.execution else {{ panic!("cleanall must execute") }};
        assert_eq!(template.safety, RawSafetyClass::Destructive);

        let empty_log = command(294);
        let RawExecutionPolicy::Executable {{ template }} = empty_log.execution else {{ panic!("empty event-log argv must execute") }};
        assert!(template.arguments.contains(&RawArgument::Empty));

        assert!(matches!(command(847).execution, RawExecutionPolicy::ReferenceOnly {{ kind: RawReferenceKind::ShellPipeline, .. }}));
        assert!(matches!(command(1932).execution, RawExecutionPolicy::ReferenceOnly {{ kind: RawReferenceKind::CompanionTool, .. }}));
    }}

    #[test]
    fn raw_catalog_does_not_present_conceptual_or_companion_sections_as_executable() {{
        let catalog = RawCatalog::builtin();
        assert_eq!(catalog.category(&RawCategoryId::new("section-29-quick-conceptual-reference").unwrap()).unwrap().kind, RawCategoryKind::Conceptual);
        assert_eq!(catalog.category(&RawCategoryId::new("section-28-yocto-companion-commands").unwrap()).unwrap().kind, RawCategoryKind::CompanionTools);
        assert_eq!(catalog.category(&RawCategoryId::new("favorites").unwrap()).unwrap().kind, RawCategoryKind::Favorites);
    }}
}}
"""
    formatted = subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=generated,
        text=True,
        check=True,
        capture_output=True,
    )
    return formatted.stdout
