use super::*;

pub(super) type CrosstermTerminal = Terminal<ratatui::backend::CrosstermBackend<io::Stdout>>;

pub(super) struct InteractiveRuntime {
    pub(super) guard: TerminalGuard,
    pub(super) terminal: CrosstermTerminal,
    pub(super) app: App,
    #[cfg(unix)]
    pub(super) daemon_runtime: Option<client_runtime::InteractiveDaemonRuntime>,
    #[cfg(unix)]
    pub(super) next_daemon_reconnect: Instant,
    pub(super) daemon_attached: bool,
    pub(super) backend_kind: Backend,
    pub(super) backend: Box<dyn BitBakeBackend>,
    pub(super) session: Session,
    pub(super) session_build_dir: PathBuf,
    pub(super) session_path: Option<PathBuf>,
    pub(super) cancellation_timeout: Duration,
    pub(super) color_forced_off: bool,
    pub(super) editor_command: Option<String>,
    pub(super) internal_tracing_capture: internal_tracing::InternalTracingCapture,

    pub(super) build_jobs: BuildJobCoordinator,
    pub(super) devtool_jobs: DevtoolJobCoordinator,
    pub(super) devtool_runner: Option<DevtoolJobRunner>,
    pub(super) pending_devtool_modify: Option<RecipeIdentity>,
    pub(super) pending_daemon_devtool_modify: Option<RecipeIdentity>,
    pub(super) pending_devtool_update: Option<RecipeIdentity>,
    pub(super) pending_devtool_finish: Option<RecipeIdentity>,
    pub(super) pending_devtool_deploy: Option<RecipeIdentity>,
    pub(super) pending_devtool_reset: Option<RecipeIdentity>,

    pub(super) signature_adapter: SignatureAdapter,
    pub(super) signature_operation: Option<SignatureBackgroundOperation>,
    pub(super) package_adapter: PackageDataAdapter,
    pub(super) package_operation: Option<PackageBackgroundOperation>,
    pub(super) image_artifact_adapter: Option<ImageArtifactAdapter>,
    pub(super) image_artifact_operation: Option<ImageArtifactBackgroundOperation>,
    pub(super) rootfs_composition_operation: Option<RootfsCompositionBackgroundOperation>,
    pub(super) global_content_search_operation: Option<GlobalContentSearchOperation>,
    pub(super) history_root: PathBuf,
    pub(super) history_load: Option<build_archive::Load>,
    pub(super) clone_operation: Option<clone_operation::CloneOperation>,
    pub(super) source_git_poller: source_git::SourceGitPoller,
    pub(super) environment_operation: Option<environment_operation::EnvironmentOperation>,

    pub(super) sdk_artifact_adapter: Option<SdkArtifactAdapter>,
    pub(super) sdk_tool_adapter: Option<SdkToolAdapter>,
    pub(super) sdk_artifact_operation: Option<SdkArtifactBackgroundOperation>,
    pub(super) sdk_capability_operation: Option<SdkCapabilityBackgroundOperation>,
    pub(super) sdk_operation: Option<SdkCliOperation>,
    pub(super) pending_sdk_build: Option<BuildRequest>,
    pub(super) qemu_inspector: QemuCapabilityInspector,
    pub(super) qemu_operation: Option<QemuCliOperation>,
    pub(super) wic_inspector: WicCapabilityInspector,
    pub(super) wic_capability_operation: Option<WicCapabilityBackgroundOperation>,
    pub(super) wic_device_inspector: WicDeviceInspector,
    pub(super) wic_device_operation: Option<WicDeviceBackgroundOperation>,
    pub(super) wic_operation: Option<WicCliOperation>,
    pub(super) test_coordinator: TestCliCoordinator,
    pub(super) pending_test_build: Option<TestSessionId>,
    pub(super) security_coordinator: SecurityCliCoordinator,
    pub(super) pending_security_build: Option<SecuritySessionId>,
    pub(super) qa_coordinator: QaCliCoordinator,
    pub(super) pending_qa_build: Option<QaSessionId>,
    pub(super) maintenance_coordinator: MaintenanceCliCoordinator,

    pub(super) telemetry_sampler: HostTelemetrySampler,
    pub(super) next_telemetry_sample: Instant,
    pub(super) telemetry_was_visible: bool,
    pub(super) next_animation_tick: Instant,
    pub(super) next_elapsed_refresh: Instant,
    pub(super) frame_interval: Duration,
    pub(super) render_scheduler: RenderScheduler,
    pub(super) environment_browser_io: environment_setup::EnvironmentBrowserIo,
    pub(super) render_measurement_started: Instant,
    pub(super) prefix_state: PrefixState,
    #[cfg(unix)]
    pub(super) termination: tokio::sync::mpsc::Receiver<()>,
}
