//! Regression tests grouped around qemu_model_normalizes_typed_runner_events_without_parsing_output.
use super::*;

mod maps_log_match_navigation_controls;
mod maps_recipe_and_task_filter_controls;
mod primary_contract;
mod qemu_adapter_normalizes_forced_cancellation_and_loss;
mod qemu_workspace_maps_launch_edit_preview_and_cancellation_keys;
mod wic_adapter_capability_crosses_app_boundary_without_parsing;
mod wic_adapter_runner_normalizes_typed_terminal_events;
mod wic_device_write_adapter_boundary_preserves_inventory_and_loss;
mod wic_device_write_and_creation_map_distinct_modal_and_artifact_keys;
mod wic_model_normalizes_typed_session_events_without_parsing_output;

mod sdk_workflow_maps_workspace_and_modal_keys_without_leakage;

mod test_workflow_test_runner_maps_keys_and_classifies_managed_bitbake_tests;

mod test_results_map_workspace_search_and_modal_keys_without_leakage;

mod test_runner_events_map_once_with_stream_and_terminal_meaning;

mod test_results_adapter_responses_map_to_identity_correlated_actions;
