[package]
name = "yoctui-bitbake"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "BitBake, process, and Yocto tool adapters for Yoctui"
publish = ["crates-io"]
[features]
test-fixtures = []
[dependencies]
async-trait.workspace = true
yoctui-model = { version = "0.1.4", path = "../yoctui-model" }
yoctui-protocol = { version = "0.1.4", path = "../yoctui-protocol" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
