//! Regression tests grouped around image_artifact_adapter_response_crosses_the_app_boundary_as_typed_action.
use super::*;

mod primary_contract;

mod ux_rootfs_protocol_crosses_app_boundary_as_typed_correlated_action;

mod pkgdata_adapter_responses_cross_the_app_boundary_as_typed_actions;

mod pkgdata_workspace_maps_search_navigation_refresh_and_context_actions;

mod signature_adapter_responses_cross_the_app_boundary_as_typed_actions;

mod typed_event_terminal_events_emit_primary_and_job_actions_once;

mod background_job_command_failure_and_disconnect_are_terminal;

mod background_job_start_failure_finishes_the_queued_job;

mod background_job_backend_error_marks_the_active_job_lost;

mod background_job_cancellation_failure_recovers_then_acknowledges;

mod background_job_coordinator_prevents_duplicate_active_builds;

mod build_environment_input_verifies_and_returns_to_dashboard;
mod exit_and_build_cancel_confirmations_trap_yes_no_and_enter;
mod maps_navigation;
mod settings_input_maps_selection_and_typed_changes;
mod ux_responsive_pane_shortcuts_map_to_focus_cycle;
mod ux_textarea_popup_input_maps_normal_insert_and_visual_commands;

mod ux_textarea_mouse_down_and_drag_map_to_typed_cursor_selection;

mod command_palette_global_shortcut_is_typed;
mod config_metadata_normalizes_typed_scope_and_history_once;
mod dialog_focus_navigation_keys_are_typed_before_cli_routing;
mod live_tasks_input_maps_selection_and_filter_controls;
mod ux_checkbox_space_toggles_but_enter_remains_primary;

mod navigator_focus_maps_selection_and_activation_without_swallowing_globals;
