//! Regression tests grouped around daemon_recovery_restores_metadata_without_claiming_live_bitbake_or_profile.
use super::*;

mod primary_contract;

mod project_profile_generation_crosses_app_boundary_as_typed_effect;

mod project_profile_input_selects_and_previews_without_starting;

mod maintenance_workflow_maps_first_class_screen_and_typed_keys;

mod maintenance_workflow_dialog_mapping_traps_typed_input;

mod maintenance_sstate_workspace_maps_only_typed_form_input;

mod maintenance_service_workspace_maps_distinct_export_and_import_forms;

mod maintenance_release_locked_workspace_maps_only_typed_form_input;

mod maintenance_release_history_workspace_maps_fields_and_toggles_without_leakage;

mod maintenance_release_archive_workspace_maps_text_toggles_and_cancel;

mod background_job_build_events_survive_navigation_and_complete;

mod dependency_graph_typed_events_map_success_partial_and_failure;
mod signature_model_typed_events_map_dump_comparison_partial_and_failure;
mod typed_event_maps_every_metadata_family_and_ignores_future_events;

mod pkgdata_model_typed_events_map_inventory_detail_partial_and_failure;

mod image_artifact_model_typed_events_map_success_partial_and_failure;
