//! Regression tests grouped around navigator_workbench_order_keeps_build_and_validation_groups_contiguous.
use super::*;

mod primary_contract;

mod navigator_groups_collapse_without_exposing_hidden_destinations;

mod collapsed_navigator_root_remains_selected_and_can_reopen;

mod collapsed_navigator_root_can_be_reselected_and_reopened;

mod command_palette_available_entry_dispatches_existing_typed_action;
mod command_palette_empty_and_disabled_activation_are_inert;
mod command_palette_search_is_case_insensitive_and_selection_is_bounded;
mod dialog_completion_queues_behind_active_dialog_and_restores_focus_after_both_close;
mod dialog_invalid_actions_leave_active_state_unchanged;
mod eviction_counts_dropped_warnings_and_errors;
mod focus_async_dialog_waits_behind_palette_then_restores;
mod focus_command_palette_restores_or_transitions_without_leaking_input;
mod focus_quit_confirmation_traps_and_restores;
mod focus_restores_exact_pane_after_nested_dialog_transitions;
mod global_content_search_rejects_stale_results_and_opens_selected_file;
mod global_search_query_is_bounded;
mod global_search_uses_case_insensitive_regex_and_reports_invalid_patterns;
mod parse_progress_tracks_current_and_total;
mod responsive_pane_focus_cycle_cannot_escape_modal_focus;
mod task_activity_transitions_parsing_to_running_without_regression;
mod theme_command_palette_entry_opens_named_picker;

mod beginning_a_build_clears_stale_build_state;
mod concept_failed_build_log_state_exposes_pause_match_and_loss_truthfully;
mod high_volume_logs_remain_within_retention_limits;
mod reducer_covers_build_lifecycle_and_log_controls;
mod task_batches_coalesce_progress_and_preserve_terminal_failures;
mod task_event_flood_bounds_active_and_completed_state_without_losing_terminal_failure;
mod unchanged_task_projection_reuses_sorted_identity_cache;
mod ux_scroll_log_eviction_and_filtering_retain_selected_identity_when_present;
