// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-18-multiconfig.l1187").unwrap(),
            category: RawCategoryId::new("section-18-multiconfig").unwrap(),
            label: "bitbake mc:<config>:<target>".into(),
            description: "Build a target from a named multiconfig.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1187").unwrap(),
                heading: "18. Multiconfig".into(),
                command: "bitbake mc:<config>:<target>".into(),
                description: "Build a target from a named multiconfig.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("config").unwrap(),
                    label: "Config".into(),
                    placeholder: "<config>".into(),
                    kind: RawParameterKind::Multiconfig,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Composed {
                        segments: vec![
                            RawArgumentSegment::Literal {
                                value: "mc:".into(),
                            },
                            RawArgumentSegment::Parameter {
                                parameter: RawParameterId::new("config").unwrap(),
                            },
                            RawArgumentSegment::Literal { value: ":".into() },
                            RawArgumentSegment::Parameter {
                                parameter: RawParameterId::new("target").unwrap(),
                            },
                        ],
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawMulticonfig,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-18-multiconfig.l1190").unwrap(),
            category: RawCategoryId::new("section-18-multiconfig").unwrap(),
            label: "bitbake mc:board1:<image>".into(),
            description: "Build an image using a multiconfig named board1.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1190").unwrap(),
                heading: "18. Multiconfig".into(),
                command: "bitbake mc:board1:<image>".into(),
                description: "Build an image using a multiconfig named board1.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("image").unwrap(),
                label: "Image".into(),
                placeholder: "<image>".into(),
                kind: RawParameterKind::Image,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Composed {
                        segments: vec![
                            RawArgumentSegment::Literal {
                                value: "mc:board1:".into(),
                            },
                            RawArgumentSegment::Parameter {
                                parameter: RawParameterId::new("image").unwrap(),
                            },
                        ],
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawMulticonfig,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-18-multiconfig.l1193").unwrap(),
            category: RawCategoryId::new("section-18-multiconfig").unwrap(),
            label: "bitbake mc:board1:<image> mc:board2:<image>".into(),
            description: "Build the same image for two multiconfigs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1193").unwrap(),
                heading: "18. Multiconfig".into(),
                command: "bitbake mc:board1:<image> mc:board2:<image>".into(),
                description: "Build the same image for two multiconfigs.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("image").unwrap(),
                label: "Image".into(),
                placeholder: "<image>".into(),
                kind: RawParameterKind::Image,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Composed {
                            segments: vec![
                                RawArgumentSegment::Literal {
                                    value: "mc:board1:".into(),
                                },
                                RawArgumentSegment::Parameter {
                                    parameter: RawParameterId::new("image").unwrap(),
                                },
                            ],
                        },
                        RawArgument::Composed {
                            segments: vec![
                                RawArgumentSegment::Literal {
                                    value: "mc:board2:".into(),
                                },
                                RawArgumentSegment::Parameter {
                                    parameter: RawParameterId::new("image").unwrap(),
                                },
                            ],
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawMulticonfig,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-18-multiconfig.l1196").unwrap(),
            category: RawCategoryId::new("section-18-multiconfig").unwrap(),
            label: "bitbake <image> mc:board1:<image> mc:board2:<image>".into(),
            description: "Build a target in the default configuration plus two extra multiconfigs."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1196").unwrap(),
                heading: "18. Multiconfig".into(),
                command: "bitbake <image> mc:board1:<image> mc:board2:<image>".into(),
                description:
                    "Build a target in the default configuration plus two extra multiconfigs."
                        .into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("image").unwrap(),
                label: "Image".into(),
                placeholder: "<image>".into(),
                kind: RawParameterKind::Image,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("image").unwrap(),
                        },
                        RawArgument::Composed {
                            segments: vec![
                                RawArgumentSegment::Literal {
                                    value: "mc:board1:".into(),
                                },
                                RawArgumentSegment::Parameter {
                                    parameter: RawParameterId::new("image").unwrap(),
                                },
                            ],
                        },
                        RawArgument::Composed {
                            segments: vec![
                                RawArgumentSegment::Literal {
                                    value: "mc:board2:".into(),
                                },
                                RawArgumentSegment::Parameter {
                                    parameter: RawParameterId::new("image").unwrap(),
                                },
                            ],
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawMulticonfig,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-18-multiconfig.l1199").unwrap(),
            category: RawCategoryId::new("section-18-multiconfig").unwrap(),
            label: "bitbake mc::<target>".into(),
            description:
                "Explicitly select the default configuration using the empty multiconfig name."
                    .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1199").unwrap(),
                heading: "18. Multiconfig".into(),
                command: "bitbake mc::<target>".into(),
                description:
                    "Explicitly select the default configuration using the empty multiconfig name."
                        .into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Composed {
                        segments: vec![
                            RawArgumentSegment::Literal {
                                value: "mc::".into(),
                            },
                            RawArgumentSegment::Parameter {
                                parameter: RawParameterId::new("target").unwrap(),
                            },
                        ],
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawMulticonfig,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
