// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0732").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake -c clean <recipe>".into(),
            description: "Remove normal recipe work/output while leaving reusable sstate intact.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0732").unwrap(),
                heading: "9.1 `clean`".into(),
                command: "bitbake -c clean <recipe>".into(),
                description: "Remove normal recipe work/output while leaving reusable sstate intact.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "clean".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0739").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake <recipe>".into(),
            description: "Rebuild after clean; BitBake may restore output from sstate instead of recompiling.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0739").unwrap(),
                heading: "9.1 `clean`".into(),
                command: "bitbake <recipe>".into(),
                description: "Rebuild after clean; BitBake may restore output from sstate instead of recompiling.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0746").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake -c cleansstate <recipe>".into(),
            description: "Remove recipe work/output plus local sstate entries.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0746").unwrap(),
                heading: "9.2 `cleansstate`".into(),
                command: "bitbake -c cleansstate <recipe>".into(),
                description: "Remove recipe work/output plus local sstate entries.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "cleansstate".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0755").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake -f -c compile <recipe>".into(),
            description: "Force the normal requested task to execute without deleting shared caches.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0755").unwrap(),
                heading: "9.2 `cleansstate`".into(),
                command: "bitbake -f -c compile <recipe>".into(),
                description: "Force the normal requested task to execute without deleting shared caches.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0762").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake -c cleanall <recipe>".into(),
            description: "Remove work/output, sstate, and source downloads for the recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0762").unwrap(),
                heading: "9.3 `cleanall`".into(),
                command: "bitbake -c cleanall <recipe>".into(),
                description: "Remove work/output, sstate, and source downloads for the recipe.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "cleanall".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0771").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake -f -c compile <recipe>".into(),
            description: "Force only do_compile to execute.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0771").unwrap(),
                heading: "9.4 Force vs clear-stamp".into(),
                command: "bitbake -f -c compile <recipe>".into(),
                description: "Force only do_compile to execute.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-09-cleaning-and-rebuilding.l0774").unwrap(),
            category: RawCategoryId::new("section-09-cleaning-and-rebuilding").unwrap(),
            label: "bitbake -C compile <recipe>".into(),
            description: "Invalidate do_compile and then run the recipe's normal default build path.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0774").unwrap(),
                heading: "9.4 Force vs clear-stamp".into(),
                command: "bitbake -C compile <recipe>".into(),
                description: "Invalidate do_compile and then run the recipe's normal default build path.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-C".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawClearStamp],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
