// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0679").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake virtual/kernel".into(),
            description: "Build the selected kernel provider.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0679").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake virtual/kernel".into(),
                description: "Build the selected kernel provider.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0682").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c menuconfig virtual/kernel".into(),
            description: "Open the kernel configuration menu.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0682").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c menuconfig virtual/kernel".into(),
                description: "Open the kernel configuration menu.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "menuconfig".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::MenuConfig],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0685").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c diffconfig virtual/kernel".into(),
            description: "Generate a configuration-difference fragment after menuconfig changes.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0685").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c diffconfig virtual/kernel".into(),
                description: "Generate a configuration-difference fragment after menuconfig changes.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "diffconfig".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0688").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c savedefconfig virtual/kernel".into(),
            description: "Save a minimal defconfig-style configuration.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0688").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c savedefconfig virtual/kernel".into(),
                description: "Save a minimal defconfig-style configuration.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "savedefconfig".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0691").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -f -c kernel_configcheck virtual/kernel".into(),
            description: "Validate the resulting kernel configuration against requested fragments/features.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0691").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -f -c kernel_configcheck virtual/kernel".into(),
                description: "Validate the resulting kernel configuration against requested fragments/features.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "kernel_configcheck".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0694").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c kernel_configme virtual/kernel".into(),
            description: "Assemble and merge kernel configuration fragments.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0694").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c kernel_configme virtual/kernel".into(),
                description: "Assemble and merge kernel configuration fragments.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "kernel_configme".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0697").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c kernel_metadata virtual/kernel".into(),
            description: "Collect kernel metadata, features, patches, and configuration fragments.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0697").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c kernel_metadata virtual/kernel".into(),
                description: "Collect kernel metadata, features, patches, and configuration fragments.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "kernel_metadata".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0700").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c kernel_checkout virtual/kernel".into(),
            description: "Prepare/check out the kernel source tree in the form expected by subsequent tasks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0700").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c kernel_checkout virtual/kernel".into(),
                description: "Prepare/check out the kernel source tree in the form expected by subsequent tasks.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "kernel_checkout".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0703").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c validate_branches virtual/kernel".into(),
            description: "Validate configured source/metadata branches.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0703").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c validate_branches virtual/kernel".into(),
                description: "Validate configured source/metadata branches.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "validate_branches".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0706").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c compile virtual/kernel".into(),
            description: "Compile the kernel.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0706").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c compile virtual/kernel".into(),
                description: "Compile the kernel.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
