// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0572").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c checkuri <recipe>".into(),
            description: "Validate the recipe's SRC_URI entries.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0572").unwrap(),
                heading: "6.1 Check SRC_URI".into(),
                command: "bitbake -c checkuri <recipe>".into(),
                description: "Validate the recipe's SRC_URI entries.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "checkuri".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0579").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c clean <recipe>".into(),
            description: "Remove recipe output from do_unpack forward while preserving sstate.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0579").unwrap(),
                heading: "6.2 Clean".into(),
                command: "bitbake -c clean <recipe>".into(),
                description: "Remove recipe output from do_unpack forward while preserving sstate.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "clean".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0586").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c cleansstate <recipe>".into(),
            description: "Remove recipe output and the recipe's local sstate cache entries.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0586").unwrap(),
                heading: "6.3 Clean shared state".into(),
                command: "bitbake -c cleansstate <recipe>".into(),
                description: "Remove recipe output and the recipe's local sstate cache entries.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "cleansstate".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0593").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c cleanall <recipe>".into(),
            description: "Remove recipe output, local sstate, and downloaded source files.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0593").unwrap(),
                heading: "6.4 Clean everything".into(),
                command: "bitbake -c cleanall <recipe>".into(),
                description: "Remove recipe output, local sstate, and downloaded source files.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "cleanall".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0600").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -f -c fetch <recipe>".into(),
            description: "Preferred way to make BitBake perform the fetch again.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0600").unwrap(),
                heading: "6.4 Clean everything".into(),
                command: "bitbake -f -c fetch <recipe>".into(),
                description: "Preferred way to make BitBake perform the fetch again.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "fetch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0607").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c devshell <recipe>".into(),
            description: "Open an interactive shell with the recipe's complete build environment.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0607").unwrap(),
                heading: "6.5 Development shell".into(),
                command: "bitbake -c devshell <recipe>".into(),
                description: "Open an interactive shell with the recipe's complete build environment.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "devshell".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::DevShell],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0614").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c pydevshell <recipe>".into(),
            description: "Open an interactive Python shell connected to the BitBake datastore/environment.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0614").unwrap(),
                heading: "6.6 Python development shell".into(),
                command: "bitbake -c pydevshell <recipe>".into(),
                description: "Open an interactive Python shell connected to the BitBake datastore/environment.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "pydevshell".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0621").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c list_image_features <image>".into(),
            description: "List IMAGE_FEATURES values available to an image recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0621").unwrap(),
                heading: "6.7 List image features".into(),
                command: "bitbake -c list_image_features <image>".into(),
                description: "List IMAGE_FEATURES values available to an image recipe.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("image").unwrap(), label: "Image".into(), placeholder: "<image>".into(), kind: RawParameterKind::Image, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "list_image_features".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("image").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0628").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake -c listtasks <recipe>".into(),
            description: "List all tasks defined for a target.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0628").unwrap(),
                heading: "6.8 List tasks".into(),
                command: "bitbake -c listtasks <recipe>".into(),
                description: "List all tasks defined for a target.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "listtasks".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeTaskList],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-06-manually-invoked-tasks.l0635").unwrap(),
            category: RawCategoryId::new("section-06-manually-invoked-tasks").unwrap(),
            label: "bitbake package-index".into(),
            description: "Build/update the package feed index through the package-index recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0635").unwrap(),
                heading: "6.9 Package feed index".into(),
                command: "bitbake package-index".into(),
                description: "Build/update the package feed index through the package-index recipe.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "package-index".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
