// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1405").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -c rootfs <image>".into(),
            description: "Build only the root filesystem stage.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1405").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -c rootfs <image>".into(),
                description: "Build only the root filesystem stage.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("image").unwrap(), label: "Image".into(), placeholder: "<image>".into(), kind: RawParameterKind::Image, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "rootfs".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("image").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1408").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -c image <image>".into(),
            description: "Build the image-generation stage.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1408").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -c image <image>".into(),
                description: "Build the image-generation stage.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("image").unwrap(), label: "Image".into(), placeholder: "<image>".into(), kind: RawParameterKind::Image, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "image".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("image").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1411").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -c image_complete <image>".into(),
            description: "Run final image completion/post-processing.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1411").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -c image_complete <image>".into(),
                description: "Run final image completion/post-processing.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("image").unwrap(), label: "Image".into(), placeholder: "<image>".into(), kind: RawParameterKind::Image, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "image_complete".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("image").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1414").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -e <image> | grep '^IMAGE_FEATURES='".into(),
            description: "Show IMAGE_FEATURES.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1414").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -e <image> | grep '^IMAGE_FEATURES='".into(),
                description: "Show IMAGE_FEATURES.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1417").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -e <image> | grep '^IMAGE_INSTALL='".into(),
            description: "Show IMAGE_INSTALL.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1417").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -e <image> | grep '^IMAGE_INSTALL='".into(),
                description: "Show IMAGE_INSTALL.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1420").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -e <image> | grep '^IMAGE_FSTYPES='".into(),
            description: "Show configured output image types.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1420").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -e <image> | grep '^IMAGE_FSTYPES='".into(),
                description: "Show configured output image types.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1423").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -e <image> | grep '^DEPLOY_DIR_IMAGE='".into(),
            description: "Show image deploy directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1423").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -e <image> | grep '^DEPLOY_DIR_IMAGE='".into(),
                description: "Show image deploy directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1426").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "bitbake -c list_image_features <image>".into(),
            description: "List available image features.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1426").unwrap(),
                heading: "23. Image debugging".into(),
                command: "bitbake -c list_image_features <image>".into(),
                description: "List available image features.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("image").unwrap(), label: "Image".into(), placeholder: "<image>".into(), kind: RawParameterKind::Image, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "list_image_features".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("image").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1429").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "find tmp/work -path \"*<image>*\" -name 'log.do_rootfs*'".into(),
            description: "Find rootfs logs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1429").unwrap(),
                heading: "23. Image debugging".into(),
                command: "find tmp/work -path \"*<image>*\" -name 'log.do_rootfs*'".into(),
                description: "Find rootfs logs.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-23-image-debugging.l1432").unwrap(),
            category: RawCategoryId::new("section-23-image-debugging").unwrap(),
            label: "find tmp/work -path \"*<image>*\" -name 'log.do_image*'".into(),
            description: "Find image-generation logs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1432").unwrap(),
                heading: "23. Image debugging".into(),
                command: "find tmp/work -path \"*<image>*\" -name 'log.do_image*'".into(),
                description: "Find image-generation logs.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
    ]
}
