// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-28-yocto-companion-commands.l1987").unwrap(),
            category: RawCategoryId::new("section-28-yocto-companion-commands").unwrap(),
            label: "devtool reset <recipe>".into(),
            description: "Remove a recipe from the devtool workspace without deleting the permanent recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1987").unwrap(),
                heading: "28.2 `devtool`".into(),
                command: "devtool reset <recipe>".into(),
                description: "Remove a recipe from the devtool workspace without deleting the permanent recipe.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-28-yocto-companion-commands.l1990").unwrap(),
            category: RawCategoryId::new("section-28-yocto-companion-commands").unwrap(),
            label: "devtool status".into(),
            description: "Show recipes currently managed by devtool.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1990").unwrap(),
                heading: "28.2 `devtool`".into(),
                command: "devtool status".into(),
                description: "Show recipes currently managed by devtool.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-28-yocto-companion-commands.l1999").unwrap(),
            category: RawCategoryId::new("section-28-yocto-companion-commands").unwrap(),
            label: "source oe-init-build-env".into(),
            description: "Initialize the OpenEmbedded build environment in the default build directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1999").unwrap(),
                heading: "28.3 Build environment initialization".into(),
                command: "source oe-init-build-env".into(),
                description: "Initialize the OpenEmbedded build environment in the default build directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-28-yocto-companion-commands.l2002").unwrap(),
            category: RawCategoryId::new("section-28-yocto-companion-commands").unwrap(),
            label: "source oe-init-build-env build-myboard".into(),
            description: "Initialize the OpenEmbedded build environment in a named build directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l2002").unwrap(),
                heading: "28.3 Build environment initialization".into(),
                command: "source oe-init-build-env build-myboard".into(),
                description: "Initialize the OpenEmbedded build environment in a named build directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-28-yocto-companion-commands.l2009").unwrap(),
            category: RawCategoryId::new("section-28-yocto-companion-commands").unwrap(),
            label: "source <setup-directory>/build/init-build-env".into(),
            description: "Source the init script generated inside a bitbake-setup build directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l2009").unwrap(),
                heading: "28.3 Build environment initialization".into(),
                command: "source <setup-directory>/build/init-build-env".into(),
                description: "Source the init script generated inside a bitbake-setup build directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
    ]
}
