// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0404").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c build <recipe>".into(),
            description: "Execute the normal top-level recipe build task.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0404").unwrap(),
                heading: "5.1 Build".into(),
                command: "bitbake -c build <recipe>".into(),
                description: "Execute the normal top-level recipe build task.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "build".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0407").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake <recipe>".into(),
            description: "Build a recipe using the default task, normally equivalent to reaching do_build.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0407").unwrap(),
                heading: "5.1 Build".into(),
                command: "bitbake <recipe>".into(),
                description: "Build a recipe using the default task, normally equivalent to reaching do_build.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0414").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c fetch <recipe>".into(),
            description: "Fetch the source files specified by SRC_URI.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0414").unwrap(),
                heading: "5.2 Fetch".into(),
                command: "bitbake -c fetch <recipe>".into(),
                description: "Fetch the source files specified by SRC_URI.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "fetch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0417").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -f -c fetch <recipe>".into(),
            description: "Force the fetch task to execute again.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0417").unwrap(),
                heading: "5.2 Fetch".into(),
                command: "bitbake -f -c fetch <recipe>".into(),
                description: "Force the fetch task to execute again.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "fetch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0424").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c unpack <recipe>".into(),
            description: "Unpack fetched source into UNPACKDIR / the recipe working area.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0424").unwrap(),
                heading: "5.3 Unpack".into(),
                command: "bitbake -c unpack <recipe>".into(),
                description: "Unpack fetched source into UNPACKDIR / the recipe working area.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "unpack".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0431").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c patch <recipe>".into(),
            description: "Locate and apply patches specified by recipe metadata.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0431").unwrap(),
                heading: "5.4 Patch".into(),
                command: "bitbake -c patch <recipe>".into(),
                description: "Locate and apply patches specified by recipe metadata.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "patch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0438").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c configure <recipe>".into(),
            description: "Configure the source tree according to the recipe and inherited build classes.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0438").unwrap(),
                heading: "5.5 Configure".into(),
                command: "bitbake -c configure <recipe>".into(),
                description: "Configure the source tree according to the recipe and inherited build classes.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "configure".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0441").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -f -c configure <recipe>".into(),
            description: "Force configuration to rerun.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0441").unwrap(),
                heading: "5.5 Configure".into(),
                command: "bitbake -f -c configure <recipe>".into(),
                description: "Force configuration to rerun.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "configure".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0448").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c compile <recipe>".into(),
            description: "Compile the recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0448").unwrap(),
                heading: "5.6 Compile".into(),
                command: "bitbake -c compile <recipe>".into(),
                description: "Compile the recipe.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
