// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0273")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -v <target>".into(),
            description:
                "Enable shell-task tracing with set -x and print bb.note() messages to stdout."
                    .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0273").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake -v <target>".into(),
                description:
                    "Enable shell-task tracing with set -x and print bb.note() messages to stdout."
                        .into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-v".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawVerbose,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0276")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --verbose <target>".into(),
            description: "Long form of -v.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0276").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake --verbose <target>".into(),
                description: "Long form of -v.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--verbose".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawVerbose,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0279")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -q <target>".into(),
            description: "Reduce terminal log output.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0279").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake -q <target>".into(),
                description: "Reduce terminal log output.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-q".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawQuiet,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0282")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -qq <target>".into(),
            description: "Reduce terminal output further.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0282").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake -qq <target>".into(),
                description: "Reduce terminal output further.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "-qq".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawQuiet,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0285")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --quiet <target>".into(),
            description: "Long form of -q.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0285").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake --quiet <target>".into(),
                description: "Long form of -q.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--quiet".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawQuiet,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0288")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -w bitbake-events.json <target>".into(),
            description: "Write build events to a BitBake JSON event log.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0288").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake -w bitbake-events.json <target>".into(),
                description: "Write build events to a BitBake JSON event log.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("event-log").unwrap(),
                    label: "Event Log".into(),
                    placeholder: "bitbake-events.json".into(),
                    kind: RawParameterKind::File,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-w".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("event-log").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawEventLog,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0291")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --write-log=bitbake-events.json <target>".into(),
            description: "Long form of -w.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0291").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake --write-log=bitbake-events.json <target>".into(),
                description: "Long form of -w.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("event-log").unwrap(),
                    label: "Event Log".into(),
                    placeholder: "bitbake-events.json".into(),
                    kind: RawParameterKind::File,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--write-log=".into(),
                            parameter: RawParameterId::new("event-log").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawEventLog,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0294")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -w '' <target>".into(),
            description: "Let BitBake automatically choose the event-log filename.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0294").unwrap(),
                heading: "3.4 Logging and output control options".into(),
                command: "bitbake -w '' <target>".into(),
                description: "Let BitBake automatically choose the event-log filename.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-w".into() },
                        RawArgument::Empty,
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawEventLog,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0301")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -B <address> --server-only".into(),
            description: "Bind the BitBake XML-RPC server to a specified address/name.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0301").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake -B <address> --server-only".into(),
                description: "Bind the BitBake XML-RPC server to a specified address/name.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("address").unwrap(),
                label: "Address".into(),
                placeholder: "<address>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-B".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("address").unwrap(),
                        },
                        RawArgument::Literal {
                            value: "--server-only".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerBind,
                            CapabilityId::BitBakeServerStart,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0304")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --bind=<address> --server-only".into(),
            description: "Long form of -B.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0304").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --bind=<address> --server-only".into(),
                description: "Long form of -B.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("address").unwrap(),
                label: "Address".into(),
                placeholder: "<address>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--bind=".into(),
                            parameter: RawParameterId::new("address").unwrap(),
                        },
                        RawArgument::Literal {
                            value: "--server-only".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerBind,
                            CapabilityId::BitBakeServerStart,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
    ]
}
