// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0956").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "bitbake -g <target>".into(),
            description: "Generate dependency graph files for a recipe or image.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0956").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "bitbake -g <target>".into(),
                description: "Generate dependency graph files for a recipe or image.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-g".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeGraphGeneration],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0959").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "bitbake -g -I virtual/kernel <target>".into(),
            description: "Generate a graph while treating virtual/kernel as already provided.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0959").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "bitbake -g -I virtual/kernel <target>".into(),
                description: "Generate a graph while treating virtual/kernel as already provided.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-g".into() },
                    RawArgument::Literal { value: "-I".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeGraphGeneration, CapabilityId::BitBakeRawIgnoreDeps],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0962").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "bitbake -g -I virtual/kernel -I <dependency> <target>".into(),
            description: "Ignore several dependencies to reduce graph clutter.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0962").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "bitbake -g -I virtual/kernel -I <dependency> <target>".into(),
                description: "Ignore several dependencies to reduce graph clutter.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("dependency").unwrap(), label: "Dependency".into(), placeholder: "<dependency>".into(), kind: RawParameterKind::Text, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-g".into() },
                    RawArgument::Literal { value: "-I".into() },
                    RawArgument::Literal { value: "virtual/kernel".into() },
                    RawArgument::Literal { value: "-I".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("dependency").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeGraphGeneration, CapabilityId::BitBakeRawIgnoreDeps],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0965").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "dot -Tpdf task-depends.dot -o task-depends.pdf".into(),
            description: "Convert the task dependency graph to PDF with Graphviz.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0965").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "dot -Tpdf task-depends.dot -o task-depends.pdf".into(),
                description: "Convert the task dependency graph to PDF with Graphviz.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0968").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "dot -Tsvg task-depends.dot -o task-depends.svg".into(),
            description: "Convert the task dependency graph to SVG.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0968").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "dot -Tsvg task-depends.dot -o task-depends.svg".into(),
                description: "Convert the task dependency graph to SVG.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0971").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "cat pn-buildlist".into(),
            description: "Inspect the simple list of providers BitBake plans to build.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0971").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "cat pn-buildlist".into(),
                description: "Inspect the simple list of providers BitBake plans to build.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-12-dependency-graphs.l0974").unwrap(),
            category: RawCategoryId::new("section-12-dependency-graphs").unwrap(),
            label: "less task-depends.dot".into(),
            description: "Inspect the generated DOT task graph.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0974").unwrap(),
                heading: "12. Dependency graphs".into(),
                command: "less task-depends.dot".into(),
                description: "Inspect the generated DOT task graph.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
    ]
}
