// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0109")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -s".into(),
            description: "Show current and preferred versions of all known recipes.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0109").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -s".into(),
                description: "Show current and preferred versions of all known recipes.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal { value: "-s".into() }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawShowVersions,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0112")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --show-versions".into(),
            description: "Long form of -s.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0112").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake --show-versions".into(),
                description: "Long form of -s.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal {
                        value: "--show-versions".into(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawShowVersions,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0115")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -e".into(),
            description: "Dump the global BitBake datastore/environment.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0115").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -e".into(),
                description: "Dump the global BitBake datastore/environment.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal { value: "-e".into() }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeEnvironmentDump,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0118")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -e <recipe>".into(),
            description: "Dump the fully expanded datastore/environment for one recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0118").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -e <recipe>".into(),
                description: "Dump the fully expanded datastore/environment for one recipe.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-e".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeEnvironmentDump,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0121")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --environment <recipe>".into(),
            description: "Long form of -e.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0121").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake --environment <recipe>".into(),
                description: "Long form of -e.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--environment".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeEnvironmentDump,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0124")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -g <target>".into(),
            description: "Generate dependency information in Graphviz DOT format.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0124").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -g <target>".into(),
                description: "Generate dependency information in Graphviz DOT format.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-g".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeGraphGeneration,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0127")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --graphviz <target>".into(),
            description: "Long form of -g.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0127").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake --graphviz <target>".into(),
                description: "Long form of -g.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--graphviz".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeGraphGeneration,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0130")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -u knotty <target>".into(),
            description: "Use the normal terminal UI.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0130").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -u knotty <target>".into(),
                description: "Use the normal terminal UI.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-u".into() },
                        RawArgument::Literal {
                            value: "knotty".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawUi],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0133")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -u ncurses <target>".into(),
            description: "Use the ncurses UI.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0133").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -u ncurses <target>".into(),
                description: "Use the ncurses UI.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-u".into() },
                        RawArgument::Literal {
                            value: "ncurses".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawUi],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0136")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -u taskexp -g <target>".into(),
            description: "Use the task dependency explorer UI.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0136").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -u taskexp -g <target>".into(),
                description: "Use the task dependency explorer UI.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-u".into() },
                        RawArgument::Literal {
                            value: "taskexp".into(),
                        },
                        RawArgument::Literal { value: "-g".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeGraphGeneration,
                            CapabilityId::BitBakeRawUi,
                        ],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
    ]
}
