// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0451").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -f -c compile <recipe>".into(),
            description: "Force compilation to rerun.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0451").unwrap(),
                heading: "5.6 Compile".into(),
                command: "bitbake -f -c compile <recipe>".into(),
                description: "Force compilation to rerun.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0454").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -v -c compile <recipe>".into(),
            description: "Trace shell commands while compiling.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0454").unwrap(),
                heading: "5.6 Compile".into(),
                command: "bitbake -v -c compile <recipe>".into(),
                description: "Trace shell commands while compiling.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-v".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeRawVerbose],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0461").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c compile_ptest_base <recipe>".into(),
            description: "Compile the software's runtime ptest suite when supported.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0461").unwrap(),
                heading: "5.7 Compile ptests".into(),
                command: "bitbake -c compile_ptest_base <recipe>".into(),
                description: "Compile the software's runtime ptest suite when supported.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "compile_ptest_base".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0468").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c configure_ptest_base <recipe>".into(),
            description: "Configure the software's ptest suite when supported.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0468").unwrap(),
                heading: "5.8 Configure ptests".into(),
                command: "bitbake -c configure_ptest_base <recipe>".into(),
                description: "Configure the software's ptest suite when supported.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "configure_ptest_base".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0475").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c install <recipe>".into(),
            description: "Install recipe output into the staging destination directory ${D}.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0475").unwrap(),
                heading: "5.9 Install".into(),
                command: "bitbake -c install <recipe>".into(),
                description: "Install recipe output into the staging destination directory ${D}.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "install".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0478").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -f -c install <recipe>".into(),
            description: "Force the install task to rerun.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0478").unwrap(),
                heading: "5.9 Install".into(),
                command: "bitbake -f -c install <recipe>".into(),
                description: "Force the install task to rerun.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "install".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0485").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c install_ptest_base <recipe>".into(),
            description: "Install ptest files into the recipe's package staging area when supported.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0485").unwrap(),
                heading: "5.10 Install ptests".into(),
                command: "bitbake -c install_ptest_base <recipe>".into(),
                description: "Install ptest files into the recipe's package staging area when supported.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "install_ptest_base".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0492").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c package <recipe>".into(),
            description: "Analyze ${D} and split installed files into packages according to PACKAGES and FILES.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0492").unwrap(),
                heading: "5.11 Package".into(),
                command: "bitbake -c package <recipe>".into(),
                description: "Analyze ${D} and split installed files into packages according to PACKAGES and FILES.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "package".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0499").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c package_qa <recipe>".into(),
            description: "Run package QA checks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0499").unwrap(),
                heading: "5.12 Package QA".into(),
                command: "bitbake -c package_qa <recipe>".into(),
                description: "Run package QA checks.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "package_qa".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
