// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0139")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -u taskexp_ncurses -g <target>".into(),
            description: "Use the ncurses task dependency explorer UI.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0139").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -u taskexp_ncurses -g <target>".into(),
                description: "Use the ncurses task dependency explorer UI.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-u".into() },
                        RawArgument::Literal {
                            value: "taskexp_ncurses".into(),
                        },
                        RawArgument::Literal { value: "-g".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeGraphGeneration,
                            CapabilityId::BitBakeRawUi,
                        ],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0142")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -u teamcity <target>".into(),
            description: "Use TeamCity-oriented output.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0142").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -u teamcity <target>".into(),
                description: "Use TeamCity-oriented output.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-u".into() },
                        RawArgument::Literal {
                            value: "teamcity".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawUi],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0145")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --ui=<ui> <target>".into(),
            description: "Long form for selecting a UI.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0145").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake --ui=<ui> <target>".into(),
                description: "Long form for selecting a UI.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("ui").unwrap(),
                    label: "Ui".into(),
                    placeholder: "<ui>".into(),
                    kind: RawParameterKind::UserInterface,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--ui=".into(),
                            parameter: RawParameterId::new("ui").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawUi],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0148")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --version".into(),
            description: "Show the BitBake version and exit.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0148").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake --version".into(),
                description: "Show the BitBake version and exit.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal {
                        value: "--version".into(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0151")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -h".into(),
            description: "Show command-line help and exit.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0151").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake -h".into(),
                description: "Show command-line help and exit.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal { value: "-h".into() }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0154")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --help".into(),
            description: "Long form of -h.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0154").unwrap(),
                heading: "3.1 General options".into(),
                command: "bitbake --help".into(),
                description: "Long form of -h.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal {
                        value: "--help".into(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0161")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -f -c <task> <recipe>".into(),
            description:
                "Force the requested target/task to execute by invalidating its existing stamp."
                    .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0161").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake -f -c <task> <recipe>".into(),
                description:
                    "Force the requested target/task to execute by invalidating its existing stamp."
                        .into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("task").unwrap(),
                    label: "Task".into(),
                    placeholder: "<task>".into(),
                    kind: RawParameterKind::Task,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("recipe").unwrap(),
                    label: "Recipe".into(),
                    placeholder: "<recipe>".into(),
                    kind: RawParameterKind::Recipe,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("task").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0164")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --force -c <task> <recipe>".into(),
            description: "Long form of -f.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0164").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake --force -c <task> <recipe>".into(),
                description: "Long form of -f.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("task").unwrap(),
                    label: "Task".into(),
                    placeholder: "<task>".into(),
                    kind: RawParameterKind::Task,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("recipe").unwrap(),
                    label: "Recipe".into(),
                    placeholder: "<recipe>".into(),
                    kind: RawParameterKind::Recipe,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--force".into(),
                        },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("task").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0167")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -c <task> <recipe>".into(),
            description: "Execute one named task for a recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0167").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake -c <task> <recipe>".into(),
                description: "Execute one named task for a recipe.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("task").unwrap(),
                    label: "Task".into(),
                    placeholder: "<task>".into(),
                    kind: RawParameterKind::Task,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("recipe").unwrap(),
                    label: "Recipe".into(),
                    placeholder: "<recipe>".into(),
                    kind: RawParameterKind::Recipe,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("task").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0170")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --cmd=<task> <recipe>".into(),
            description: "Long form of -c.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0170").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake --cmd=<task> <recipe>".into(),
                description: "Long form of -c.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("task").unwrap(),
                    label: "Task".into(),
                    placeholder: "<task>".into(),
                    kind: RawParameterKind::Task,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("recipe").unwrap(),
                    label: "Recipe".into(),
                    placeholder: "<recipe>".into(),
                    kind: RawParameterKind::Recipe,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--cmd=".into(),
                            parameter: RawParameterId::new("task").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
