// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0709").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c compile_kernelmodules virtual/kernel".into(),
            description: "Compile kernel modules.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0709").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c compile_kernelmodules virtual/kernel".into(),
                description: "Compile kernel modules.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile_kernelmodules".into(),
                        },
                        RawArgument::Literal {
                            value: "virtual/kernel".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0712").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c shared_workdir virtual/kernel".into(),
            description:
                "Populate the shared kernel work directory used by out-of-tree/module builds."
                    .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0712").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c shared_workdir virtual/kernel".into(),
                description:
                    "Populate the shared kernel work directory used by out-of-tree/module builds."
                        .into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "shared_workdir".into(),
                        },
                        RawArgument::Literal {
                            value: "virtual/kernel".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0715").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c sizecheck virtual/kernel".into(),
            description: "Run the kernel image size check when KERNEL_IMAGE_MAXSIZE is configured."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0715").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c sizecheck virtual/kernel".into(),
                description:
                    "Run the kernel image size check when KERNEL_IMAGE_MAXSIZE is configured."
                        .into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "sizecheck".into(),
                        },
                        RawArgument::Literal {
                            value: "virtual/kernel".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0718").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c strip virtual/kernel".into(),
            description: "Strip configured nonessential sections from vmlinux when supported."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0718").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c strip virtual/kernel".into(),
                description: "Strip configured nonessential sections from vmlinux when supported."
                    .into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "strip".into(),
                        },
                        RawArgument::Literal {
                            value: "virtual/kernel".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-08-kernel-related-tasks.l0721").unwrap(),
            category: RawCategoryId::new("section-08-kernel-related-tasks").unwrap(),
            label: "bitbake -c deploy virtual/kernel".into(),
            description: "Deploy kernel artifacts.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0721").unwrap(),
                heading: "8. Kernel-related tasks".into(),
                command: "bitbake -c deploy virtual/kernel".into(),
                description: "Deploy kernel artifacts.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "deploy".into(),
                        },
                        RawArgument::Literal {
                            value: "virtual/kernel".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
