// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0506").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c recipe_qa <recipe>".into(),
            description: "Run metadata-only recipe QA checks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0506").unwrap(),
                heading: "5.13 Recipe QA".into(),
                command: "bitbake -c recipe_qa <recipe>".into(),
                description: "Run metadata-only recipe QA checks.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "recipe_qa".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0513").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c packagedata <recipe>".into(),
            description: "Write package metadata into the global package-data area.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0513").unwrap(),
                heading: "5.14 Package data".into(),
                command: "bitbake -c packagedata <recipe>".into(),
                description: "Write package metadata into the global package-data area.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "packagedata".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0520").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c package_write_rpm <recipe>".into(),
            description: "Create RPM package files when RPM packaging is enabled.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0520").unwrap(),
                heading: "5.15 Package backends".into(),
                command: "bitbake -c package_write_rpm <recipe>".into(),
                description: "Create RPM package files when RPM packaging is enabled.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "package_write_rpm".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0523").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c package_write_ipk <recipe>".into(),
            description: "Create IPK package files when IPK packaging is enabled.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0523").unwrap(),
                heading: "5.15 Package backends".into(),
                command: "bitbake -c package_write_ipk <recipe>".into(),
                description: "Create IPK package files when IPK packaging is enabled.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "package_write_ipk".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0526").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c package_write_deb <recipe>".into(),
            description: "Create DEB package files when Debian packaging is enabled.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0526").unwrap(),
                heading: "5.15 Package backends".into(),
                command: "bitbake -c package_write_deb <recipe>".into(),
                description: "Create DEB package files when Debian packaging is enabled.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "package_write_deb".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0533").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c populate_sysroot <recipe>".into(),
            description: "Stage the recipe's development/build files into its sysroot output."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0533").unwrap(),
                heading: "5.16 Populate sysroot".into(),
                command: "bitbake -c populate_sysroot <recipe>".into(),
                description: "Stage the recipe's development/build files into its sysroot output."
                    .into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "populate_sysroot".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0540").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c prepare_recipe_sysroot <recipe>".into(),
            description: "Populate recipe-sysroot and recipe-sysroot-native from DEPENDS.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0540").unwrap(),
                heading: "5.17 Prepare recipe sysroot".into(),
                command: "bitbake -c prepare_recipe_sysroot <recipe>".into(),
                description: "Populate recipe-sysroot and recipe-sysroot-native from DEPENDS."
                    .into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "prepare_recipe_sysroot".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0547").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c populate_lic <recipe>".into(),
            description: "Collect and stage license information for the recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0547").unwrap(),
                heading: "5.18 License data".into(),
                command: "bitbake -c populate_lic <recipe>".into(),
                description: "Collect and stage license information for the recipe.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "populate_lic".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0554").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c deploy <recipe>".into(),
            description: "Deploy recipe output when the recipe implements do_deploy.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0554").unwrap(),
                heading: "5.19 Deploy".into(),
                command: "bitbake -c deploy <recipe>".into(),
                description: "Deploy recipe output when the recipe implements do_deploy.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "deploy".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-05-normal-openembedded-recipe-tasks.l0561").unwrap(),
            category: RawCategoryId::new("section-05-normal-openembedded-recipe-tasks").unwrap(),
            label: "bitbake -c rm_work <recipe>".into(),
            description: "Run the rm_work cleanup task when available/enabled.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0561").unwrap(),
                heading: "5.20 Remove work".into(),
                command: "bitbake -c rm_work <recipe>".into(),
                description: "Run the rm_work cleanup task when available/enabled.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "rm_work".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
