// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1441").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^TMPDIR='".into(),
            description: "Show the complete top-level temporary build directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1441").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^TMPDIR='".into(),
                description: "Show the complete top-level temporary build directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1444").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^BASE_WORKDIR='".into(),
            description: "Show the work-directory base.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1444").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^BASE_WORKDIR='".into(),
                description: "Show the work-directory base.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1447").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^DL_DIR='".into(),
            description: "Show source download cache.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1447").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^DL_DIR='".into(),
                description: "Show source download cache.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1450").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^SSTATE_DIR='".into(),
            description: "Show shared-state cache.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1450").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^SSTATE_DIR='".into(),
                description: "Show shared-state cache.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1453").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^PKGDATA_DIR='".into(),
            description: "Show package-data directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1453").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^PKGDATA_DIR='".into(),
                description: "Show package-data directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1456").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^DEPLOY_DIR_IMAGE='".into(),
            description: "Show image deployment directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1456").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^DEPLOY_DIR_IMAGE='".into(),
                description: "Show image deployment directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1459").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^DEPLOY_DIR_RPM='".into(),
            description: "Show RPM deployment directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1459").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^DEPLOY_DIR_RPM='".into(),
                description: "Show RPM deployment directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1462").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^DEPLOY_DIR_IPK='".into(),
            description: "Show IPK deployment directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1462").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^DEPLOY_DIR_IPK='".into(),
                description: "Show IPK deployment directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1465").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e | grep '^DEPLOY_DIR_DEB='".into(),
            description: "Show DEB deployment directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1465").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e | grep '^DEPLOY_DIR_DEB='".into(),
                description: "Show DEB deployment directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1468").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^WORKDIR='".into(),
            description: "Show recipe-specific WORKDIR.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1468").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^WORKDIR='".into(),
                description: "Show recipe-specific WORKDIR.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1471").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^S='".into(),
            description: "Show recipe source directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1471").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^S='".into(),
                description: "Show recipe source directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1474").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^B='".into(),
            description: "Show recipe build directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1474").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^B='".into(),
                description: "Show recipe build directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1477").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^D='".into(),
            description: "Show recipe install staging directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1477").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^D='".into(),
                description: "Show recipe install staging directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1480").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^T='".into(),
            description: "Show recipe temporary task/log directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1480").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^T='".into(),
                description: "Show recipe temporary task/log directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1483").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^RECIPE_SYSROOT='".into(),
            description: "Show recipe-specific sysroot.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1483").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^RECIPE_SYSROOT='".into(),
                description: "Show recipe-specific sysroot.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-24-useful-paths-and-variables.l1486").unwrap(),
            category: RawCategoryId::new("section-24-useful-paths-and-variables").unwrap(),
            label: "bitbake -e <recipe> | grep '^RECIPE_SYSROOT_NATIVE='".into(),
            description: "Show native recipe sysroot.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1486").unwrap(),
                heading: "24. Useful paths and variables".into(),
                command: "bitbake -e <recipe> | grep '^RECIPE_SYSROOT_NATIVE='".into(),
                description: "Show native recipe sysroot.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
    ]
}
