// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0173").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake -C <task> <recipe>".into(),
            description: "Invalidate a named task stamp, then execute the target's normal default task.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0173").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake -C <task> <recipe>".into(),
                description: "Invalidate a named task stamp, then execute the target's normal default task.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-C".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawClearStamp],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0176").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake --clear-stamp=<task> <recipe>".into(),
            description: "Long form of -C.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0176").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake --clear-stamp=<task> <recipe>".into(),
                description: "Long form of -C.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::JoinedParameter { prefix: "--clear-stamp=".into(), parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawClearStamp],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0179").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake <target> --runall=<task>".into(),
            description: "Run a named task for every applicable recipe in the target's task graph.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0179").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake <target> --runall=<task>".into(),
                description: "Run a named task for every applicable recipe in the target's task graph.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() },
                    RawArgument::JoinedParameter { prefix: "--runall=".into(), parameter: RawParameterId::new("task").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawRunAll],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0182").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake <target> --runonly=<task>".into(),
            description: "Run only a named task throughout the target graph plus dependencies required by those tasks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0182").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake <target> --runonly=<task>".into(),
                description: "Run only a named task throughout the target graph plus dependencies required by those tasks.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() },
                    RawArgument::JoinedParameter { prefix: "--runonly=".into(), parameter: RawParameterId::new("task").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawRunOnly],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0185").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake --no-setscene <target>".into(),
            description: "Do not run setscene tasks and ignore sstate restoration.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0185").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake --no-setscene <target>".into(),
                description: "Do not run setscene tasks and ignore sstate restoration.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "--no-setscene".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawNoSetscene],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0188").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake --skip-setscene <target>".into(),
            description: "Skip new setscene execution but keep output already restored from sstate.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0188").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake --skip-setscene <target>".into(),
                description: "Skip new setscene execution but keep output already restored from sstate.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "--skip-setscene".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawSkipSetscene],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0191").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake --setscene-only <target>".into(),
            description: "Execute only setscene tasks and no normal build tasks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0191").unwrap(),
                heading: "3.2 Task control options".into(),
                command: "bitbake --setscene-only <target>".into(),
                description: "Execute only setscene tasks and no normal build tasks.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "--setscene-only".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawSetsceneOnly],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0198").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake -n <target>".into(),
            description: "Perform a dry run: construct what would run without executing real tasks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0198").unwrap(),
                heading: "3.3 Execution control options".into(),
                command: "bitbake -n <target>".into(),
                description: "Perform a dry run: construct what would run without executing real tasks.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-n".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawDryRun],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0201").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake --dry-run <target>".into(),
            description: "Long form of -n.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0201").unwrap(),
                heading: "3.3 Execution control options".into(),
                command: "bitbake --dry-run <target>".into(),
                description: "Long form of -n.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("target").unwrap(), label: "Target".into(), placeholder: "<target>".into(), kind: RawParameterKind::Target, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "--dry-run".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("target").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawDryRun],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0204").unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference").unwrap(),
            label: "bitbake -p".into(),
            description: "Parse all recipes/metadata and stop before task execution.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0204").unwrap(),
                heading: "3.3 Execution control options".into(),
                command: "bitbake -p".into(),
                description: "Parse all recipes/metadata and stop before task execution.".into(),
            },
            parameters: vec![
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-p".into() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawParseOnly],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
    ]
}
