// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0307")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -T <seconds> <target>".into(),
            description: "Set the server inactivity timeout in seconds.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0307").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake -T <seconds> <target>".into(),
                description: "Set the server inactivity timeout in seconds.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("seconds").unwrap(),
                    label: "Seconds".into(),
                    placeholder: "<seconds>".into(),
                    kind: RawParameterKind::Integer,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-T".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("seconds").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerIdleTimeout,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0310")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -T -1 <target>".into(),
            description: "Disable automatic server unloading due to inactivity.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0310").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake -T -1 <target>".into(),
                description: "Disable automatic server unloading due to inactivity.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-T".into() },
                        RawArgument::Literal { value: "-1".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerIdleTimeout,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0313")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --idle-timeout=<seconds> <target>".into(),
            description: "Long form of -T.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0313").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --idle-timeout=<seconds> <target>".into(),
                description: "Long form of -T.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("seconds").unwrap(),
                    label: "Seconds".into(),
                    placeholder: "<seconds>".into(),
                    kind: RawParameterKind::Integer,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--idle-timeout=".into(),
                            parameter: RawParameterId::new("seconds").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerIdleTimeout,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0316")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --remote-server=<server>".into(),
            description: "Connect to an already running BitBake server.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0316").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --remote-server=<server>".into(),
                description: "Connect to an already running BitBake server.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("server").unwrap(),
                label: "Server".into(),
                placeholder: "<server>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::JoinedParameter {
                        prefix: "--remote-server=".into(),
                        parameter: RawParameterId::new("server").unwrap(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0319")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake -m".into(),
            description: "Terminate any running BitBake server associated with the environment."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0319").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake -m".into(),
                description:
                    "Terminate any running BitBake server associated with the environment.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal { value: "-m".into() }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeServerStop,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0322")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --kill-server".into(),
            description: "Long form of -m.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0322").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --kill-server".into(),
                description: "Long form of -m.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal {
                        value: "--kill-server".into(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeServerStop,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0325")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --token=<token> --remote-server=<server>".into(),
            description: "Supply an XML-RPC connection token when connecting to a remote server."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0325").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --token=<token> --remote-server=<server>".into(),
                description:
                    "Supply an XML-RPC connection token when connecting to a remote server.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("token").unwrap(),
                    label: "Token".into(),
                    placeholder: "<token>".into(),
                    kind: RawParameterKind::Text,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("server").unwrap(),
                    label: "Server".into(),
                    placeholder: "<server>".into(),
                    kind: RawParameterKind::Text,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--token=".into(),
                            parameter: RawParameterId::new("token").unwrap(),
                        },
                        RawArgument::JoinedParameter {
                            prefix: "--remote-server=".into(),
                            parameter: RawParameterId::new("server").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                            CapabilityId::BitBakeRawServerToken,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0328")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --observe-only --remote-server=<server>".into(),
            description: "Connect to a server as an observation-only client.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0328").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --observe-only --remote-server=<server>".into(),
                description: "Connect to a server as an observation-only client.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("server").unwrap(),
                label: "Server".into(),
                placeholder: "<server>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--observe-only".into(),
                        },
                        RawArgument::JoinedParameter {
                            prefix: "--remote-server=".into(),
                            parameter: RawParameterId::new("server").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                            CapabilityId::BitBakeRawServerObserve,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0331")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --status-only --remote-server=<server>".into(),
            description: "Query only the status of a remote BitBake server.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0331").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --status-only --remote-server=<server>".into(),
                description: "Query only the status of a remote BitBake server.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("server").unwrap(),
                label: "Server".into(),
                placeholder: "<server>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--status-only".into(),
                        },
                        RawArgument::JoinedParameter {
                            prefix: "--remote-server=".into(),
                            parameter: RawParameterId::new("server").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                            CapabilityId::BitBakeServerStatus,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-03-complete-bitbake-2-18-cli-option-reference.l0334")
                .unwrap(),
            category: RawCategoryId::new("section-03-complete-bitbake-2-18-cli-option-reference")
                .unwrap(),
            label: "bitbake --server-only".into(),
            description: "Start only the BitBake cooker/server process without a normal UI client."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0334").unwrap(),
                heading: "3.5 Server options".into(),
                command: "bitbake --server-only".into(),
                description:
                    "Start only the BitBake cooker/server process without a normal UI client."
                        .into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal {
                        value: "--server-only".into(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeServerStart,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
    ]
}
