// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1700").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -p".into(),
            description: "Check whether the complete metadata set parses.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1700").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -p".into(),
                description: "Check whether the complete metadata set parses.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal { value: "-p".into() }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawParseOnly,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1703").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake <target>".into(),
            description: "Build a recipe or image.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1703").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake <target>".into(),
                description: "Build a recipe or image.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Parameter {
                        parameter: RawParameterId::new("target").unwrap(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1706").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -s | grep '<recipe>'".into(),
            description: "See whether BitBake knows a recipe and which version is preferred."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1706").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -s | grep '<recipe>'".into(),
                description: "See whether BitBake knows a recipe and which version is preferred."
                    .into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1709").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c listtasks <recipe>".into(),
            description: "List every task available to one recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1709").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c listtasks <recipe>".into(),
                description: "List every task available to one recipe.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "listtasks".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeTaskList,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1712").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c fetch <recipe>".into(),
            description: "Fetch source.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1712").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c fetch <recipe>".into(),
                description: "Fetch source.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "fetch".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1715").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c unpack <recipe>".into(),
            description: "Unpack source.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1715").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c unpack <recipe>".into(),
                description: "Unpack source.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "unpack".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1718").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c patch <recipe>".into(),
            description: "Apply patches.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1718").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c patch <recipe>".into(),
                description: "Apply patches.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "patch".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1721").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c configure <recipe>".into(),
            description: "Configure.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1721").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c configure <recipe>".into(),
                description: "Configure.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "configure".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1724").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c compile <recipe>".into(),
            description: "Compile.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1724").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c compile <recipe>".into(),
                description: "Compile.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1727").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -f -c compile <recipe>".into(),
            description: "Force compile.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1727").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -f -c compile <recipe>".into(),
                description: "Force compile.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
