// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1730").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c install <recipe>".into(),
            description: "Install into ${D}.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1730").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c install <recipe>".into(),
                description: "Install into ${D}.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "install".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1733").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c package_qa <recipe>".into(),
            description: "Run package QA.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1733").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c package_qa <recipe>".into(),
                description: "Run package QA.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "package_qa".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1736").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -c devshell <recipe>".into(),
            description: "Open the recipe development shell.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1736").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -c devshell <recipe>".into(),
                description: "Open the recipe development shell.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "devshell".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::DevShell,
                        ],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1739").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -e <recipe>".into(),
            description: "Dump the complete expanded recipe datastore.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1739").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -e <recipe>".into(),
                description: "Dump the complete expanded recipe datastore.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-e".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeEnvironmentDump,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1742").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -e <recipe> | grep '^WORKDIR='".into(),
            description: "Find WORKDIR.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1742").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -e <recipe> | grep '^WORKDIR='".into(),
                description: "Find WORKDIR.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1745").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -e <recipe> | grep '^S='".into(),
            description: "Find the source directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1745").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -e <recipe> | grep '^S='".into(),
                description: "Find the source directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1748").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -n <target>".into(),
            description: "See what BitBake would execute without executing it.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1748").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -n <target>".into(),
                description: "See what BitBake would execute without executing it.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-n".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDryRun,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1751").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -g <target>".into(),
            description: "Generate a dependency graph.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1751").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -g <target>".into(),
                description: "Generate a dependency graph.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-g".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeGraphGeneration,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1754").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -S printdiff <recipe>".into(),
            description: "Explain why task signatures changed.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1754").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -S printdiff <recipe>".into(),
                description: "Explain why task signatures changed.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-S".into() },
                        RawArgument::Literal {
                            value: "printdiff".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDumpSignatures,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-26-commands-worth-memorizing.l1757").unwrap(),
            category: RawCategoryId::new("section-26-commands-worth-memorizing").unwrap(),
            label: "bitbake -k <target>".into(),
            description: "Continue independent work after one failure.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1757").unwrap(),
                heading: "26. Commands worth memorizing".into(),
                command: "bitbake -k <target>".into(),
                description: "Continue independent work after one failure.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-k".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawContinue,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
