// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1236").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -c checkuri <recipe>".into(),
            description: "Validate SRC_URI without carrying out a normal build.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1236").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -c checkuri <recipe>".into(),
                description: "Validate SRC_URI without carrying out a normal build.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "checkuri".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1239").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -c fetch <recipe>".into(),
            description: "Fetch source.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1239").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -c fetch <recipe>".into(),
                description: "Fetch source.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "fetch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1242").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -f -c fetch <recipe>".into(),
            description: "Force source to be fetched again.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1242").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -f -c fetch <recipe>".into(),
                description: "Force source to be fetched again.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "fetch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1245").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -c unpack <recipe>".into(),
            description: "Unpack fetched source.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1245").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -c unpack <recipe>".into(),
                description: "Unpack fetched source.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "unpack".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1248").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -c patch <recipe>".into(),
            description: "Apply patches.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1248").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -c patch <recipe>".into(),
                description: "Apply patches.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "patch".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1251").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^SRC_URI='".into(),
            description: "Show the configured source URIs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1251").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -e <recipe> | grep '^SRC_URI='".into(),
                description: "Show the configured source URIs.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1254").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^SRCREV='".into(),
            description: "Show the configured source revision.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1254").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -e <recipe> | grep '^SRCREV='".into(),
                description: "Show the configured source revision.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1257").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^S='".into(),
            description: "Show the source directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1257").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -e <recipe> | grep '^S='".into(),
                description: "Show the source directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1260").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^UNPACKDIR='".into(),
            description: "Show the unpack directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1260").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -e <recipe> | grep '^UNPACKDIR='".into(),
                description: "Show the unpack directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1263").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "bitbake -e | grep '^DL_DIR='".into(),
            description: "Show the download cache directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1263").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "bitbake -e | grep '^DL_DIR='".into(),
                description: "Show the download cache directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1266").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "find tmp/work -path \"*<recipe>*\" -name 'log.do_fetch*'".into(),
            description: "Find fetch logs for the recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1266").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "find tmp/work -path \"*<recipe>*\" -name 'log.do_fetch*'".into(),
                description: "Find fetch logs for the recipe.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1269").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "find tmp/work -path \"*<recipe>*\" -name 'log.do_unpack*'".into(),
            description: "Find unpack logs for the recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1269").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "find tmp/work -path \"*<recipe>*\" -name 'log.do_unpack*'".into(),
                description: "Find unpack logs for the recipe.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-20-fetch-source-debugging.l1272").unwrap(),
            category: RawCategoryId::new("section-20-fetch-source-debugging").unwrap(),
            label: "find tmp/work -path \"*<recipe>*\" -name 'log.do_patch*'".into(),
            description: "Find patch logs for the recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1272").unwrap(),
                heading: "20. Fetch/source debugging".into(),
                command: "find tmp/work -path \"*<recipe>*\" -name 'log.do_patch*'".into(),
                description: "Find patch logs for the recipe.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
    ]
}
