// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-13-signatures-and-rebuild-analysis.l0992").unwrap(),
            category: RawCategoryId::new("section-13-signatures-and-rebuild-analysis").unwrap(),
            label: "bitbake -S none <target>".into(),
            description: "Dump task signature construction data without executing tasks.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0992").unwrap(),
                heading: "13. Signatures and rebuild analysis".into(),
                command: "bitbake -S none <target>".into(),
                description: "Dump task signature construction data without executing tasks."
                    .into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-S".into() },
                        RawArgument::Literal {
                            value: "none".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDumpSignatures,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-13-signatures-and-rebuild-analysis.l0995").unwrap(),
            category: RawCategoryId::new("section-13-signatures-and-rebuild-analysis").unwrap(),
            label: "bitbake -S printdiff <target>".into(),
            description: "Compare current task signatures to the newest local/sstate signatures."
                .into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0995").unwrap(),
                heading: "13. Signatures and rebuild analysis".into(),
                command: "bitbake -S printdiff <target>".into(),
                description:
                    "Compare current task signatures to the newest local/sstate signatures.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-S".into() },
                        RawArgument::Literal {
                            value: "printdiff".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDumpSignatures,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-13-signatures-and-rebuild-analysis.l0998").unwrap(),
            category: RawCategoryId::new("section-13-signatures-and-rebuild-analysis").unwrap(),
            label: "bitbake -S printdiff <recipe>".into(),
            description: "Investigate why one recipe unexpectedly wants to rebuild.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0998").unwrap(),
                heading: "13. Signatures and rebuild analysis".into(),
                command: "bitbake -S printdiff <recipe>".into(),
                description: "Investigate why one recipe unexpectedly wants to rebuild.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-S".into() },
                        RawArgument::Literal {
                            value: "printdiff".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDumpSignatures,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-13-signatures-and-rebuild-analysis.l1001").unwrap(),
            category: RawCategoryId::new("section-13-signatures-and-rebuild-analysis").unwrap(),
            label: "bitbake -S printdiff <image>".into(),
            description: "Investigate rebuild reasons for an entire image.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1001").unwrap(),
                heading: "13. Signatures and rebuild analysis".into(),
                command: "bitbake -S printdiff <image>".into(),
                description: "Investigate rebuild reasons for an entire image.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("image").unwrap(),
                label: "Image".into(),
                placeholder: "<image>".into(),
                kind: RawParameterKind::Image,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-S".into() },
                        RawArgument::Literal {
                            value: "printdiff".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("image").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDumpSignatures,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
    ]
}
