// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-one-screen-emergency-reference.l2264").unwrap(),
            category: RawCategoryId::new("section-one-screen-emergency-reference").unwrap(),
            label: "bitbake-layers show-appends".into(),
            description: "Show matching appends.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l2264").unwrap(),
                heading: "One-screen emergency reference".into(),
                command: "bitbake-layers show-appends".into(),
                description: "Show matching appends.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
    ]
}
