// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1124").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake --server-only".into(),
            description: "Start BitBake in server-only mode.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1124").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake --server-only".into(),
                description: "Start BitBake in server-only mode.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal {
                        value: "--server-only".into(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeServerStart,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1127").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake -B <address> --server-only".into(),
            description: "Bind a server-only instance to a specified address/name.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1127").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake -B <address> --server-only".into(),
                description: "Bind a server-only instance to a specified address/name.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("address").unwrap(),
                label: "Address".into(),
                placeholder: "<address>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-B".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("address").unwrap(),
                        },
                        RawArgument::Literal {
                            value: "--server-only".into(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerBind,
                            CapabilityId::BitBakeServerStart,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1130").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake -T <seconds> <target>".into(),
            description: "Set a custom server idle timeout.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1130").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake -T <seconds> <target>".into(),
                description: "Set a custom server idle timeout.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("seconds").unwrap(),
                    label: "Seconds".into(),
                    placeholder: "<seconds>".into(),
                    kind: RawParameterKind::Integer,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-T".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("seconds").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerIdleTimeout,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1133").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake -T -1 <target>".into(),
            description: "Prevent inactivity-based server unloading.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1133").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake -T -1 <target>".into(),
                description: "Prevent inactivity-based server unloading.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-T".into() },
                        RawArgument::Literal { value: "-1".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerIdleTimeout,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1136").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake --remote-server=<server>".into(),
            description: "Connect to a remote BitBake server.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1136").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake --remote-server=<server>".into(),
                description: "Connect to a remote BitBake server.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("server").unwrap(),
                label: "Server".into(),
                placeholder: "<server>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::JoinedParameter {
                        prefix: "--remote-server=".into(),
                        parameter: RawParameterId::new("server").unwrap(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1139").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake --token=<token> --remote-server=<server>".into(),
            description: "Connect with an XML-RPC token.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1139").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake --token=<token> --remote-server=<server>".into(),
                description: "Connect with an XML-RPC token.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("token").unwrap(),
                    label: "Token".into(),
                    placeholder: "<token>".into(),
                    kind: RawParameterKind::Text,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("server").unwrap(),
                    label: "Server".into(),
                    placeholder: "<server>".into(),
                    kind: RawParameterKind::Text,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::JoinedParameter {
                            prefix: "--token=".into(),
                            parameter: RawParameterId::new("token").unwrap(),
                        },
                        RawArgument::JoinedParameter {
                            prefix: "--remote-server=".into(),
                            parameter: RawParameterId::new("server").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                            CapabilityId::BitBakeRawServerToken,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1142").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake --observe-only --remote-server=<server>".into(),
            description: "Connect as an observer only.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1142").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake --observe-only --remote-server=<server>".into(),
                description: "Connect as an observer only.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("server").unwrap(),
                label: "Server".into(),
                placeholder: "<server>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--observe-only".into(),
                        },
                        RawArgument::JoinedParameter {
                            prefix: "--remote-server=".into(),
                            parameter: RawParameterId::new("server").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                            CapabilityId::BitBakeRawServerObserve,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1145").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake --status-only --remote-server=<server>".into(),
            description: "Query remote-server status only.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1145").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake --status-only --remote-server=<server>".into(),
                description: "Query remote-server status only.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("server").unwrap(),
                label: "Server".into(),
                placeholder: "<server>".into(),
                kind: RawParameterKind::Text,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "--status-only".into(),
                        },
                        RawArgument::JoinedParameter {
                            prefix: "--remote-server=".into(),
                            parameter: RawParameterId::new("server").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawServerRemote,
                            CapabilityId::BitBakeServerStatus,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-16-server-client-options.l1148").unwrap(),
            category: RawCategoryId::new("section-16-server-client-options").unwrap(),
            label: "bitbake -m".into(),
            description: "Kill the running BitBake server.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1148").unwrap(),
                heading: "16. Server/client options".into(),
                command: "bitbake -m".into(),
                description: "Kill the running BitBake server.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Literal { value: "-m".into() }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeServerStop,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::ServerLifecycle,
                },
            },
        },
    ]
}
