// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1060").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -D <target>".into(),
            description: "Show bb.debug(1, ...) messages on stdout.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1060").unwrap(),
                heading: "15.1 BitBake debug level".into(),
                command: "bitbake -D <target>".into(),
                description: "Show bb.debug(1, ...) messages on stdout.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-D".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDebug,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1063").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -DD <target>".into(),
            description: "Show debug levels 1 and 2.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1063").unwrap(),
                heading: "15.1 BitBake debug level".into(),
                command: "bitbake -DD <target>".into(),
                description: "Show debug levels 1 and 2.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "-DD".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDebug,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1066").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -DDD <target>".into(),
            description: "Show debug levels 1 through 3.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1066").unwrap(),
                heading: "15.1 BitBake debug level".into(),
                command: "bitbake -DDD <target>".into(),
                description: "Show debug levels 1 through 3.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "-DDD".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDebug,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1073").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -v <target>".into(),
            description: "Trace shell task execution and expose bb.note() messages.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1073").unwrap(),
                heading: "15.2 Verbose task tracing".into(),
                command: "bitbake -v <target>".into(),
                description: "Trace shell task execution and expose bb.note() messages.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-v".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawVerbose,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1076").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -v -c compile <recipe>".into(),
            description: "Trace shell execution for one compile task.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1076").unwrap(),
                heading: "15.2 Verbose task tracing".into(),
                command: "bitbake -v -c compile <recipe>".into(),
                description: "Trace shell execution for one compile task.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-v".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeRawVerbose,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1079").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -v -f -c compile <recipe>".into(),
            description: "Force and trace compilation.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1079").unwrap(),
                heading: "15.2 Verbose task tracing".into(),
                command: "bitbake -v -f -c compile <recipe>".into(),
                description: "Force and trace compilation.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-v".into() },
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                            CapabilityId::BitBakeRawVerbose,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1086").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -q <target>".into(),
            description: "Reduce terminal output.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1086").unwrap(),
                heading: "15.3 Quiet mode".into(),
                command: "bitbake -q <target>".into(),
                description: "Reduce terminal output.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-q".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawQuiet,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1089").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -qq <target>".into(),
            description: "Reduce terminal output further.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1089").unwrap(),
                heading: "15.3 Quiet mode".into(),
                command: "bitbake -qq <target>".into(),
                description: "Reduce terminal output further.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("target").unwrap(),
                label: "Target".into(),
                placeholder: "<target>".into(),
                kind: RawParameterKind::Target,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal {
                            value: "-qq".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawQuiet,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1096").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -l <domain> <target>".into(),
            description: "Enable debug logging only for a selected BitBake logging domain.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1096").unwrap(),
                heading: "15.4 Logging domains".into(),
                command: "bitbake -l <domain> <target>".into(),
                description: "Enable debug logging only for a selected BitBake logging domain."
                    .into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("domain").unwrap(),
                    label: "Domain".into(),
                    placeholder: "<domain>".into(),
                    kind: RawParameterKind::Text,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-l".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("domain").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawLogDomains,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-15-debug-and-logging.l1103").unwrap(),
            category: RawCategoryId::new("section-15-debug-and-logging").unwrap(),
            label: "bitbake -w events.json <target>".into(),
            description: "Write the BitBake event stream to JSON.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1103").unwrap(),
                heading: "15.5 Event log".into(),
                command: "bitbake -w events.json <target>".into(),
                description: "Write the BitBake event stream to JSON.".into(),
            },
            parameters: vec![
                RawParameter {
                    id: RawParameterId::new("event-log").unwrap(),
                    label: "Event Log".into(),
                    placeholder: "events.json".into(),
                    kind: RawParameterKind::File,
                    presence: RawParameterPresence::Required,
                },
                RawParameter {
                    id: RawParameterId::new("target").unwrap(),
                    label: "Target".into(),
                    placeholder: "<target>".into(),
                    kind: RawParameterKind::Target,
                    presence: RawParameterPresence::Required,
                },
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-w".into() },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("event-log").unwrap(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("target").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawEventLog,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
