// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1639").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -f -c install <recipe>".into(),
            description: "Re-run installation.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1639").unwrap(),
                heading: "25.8 Packaging failure".into(),
                command: "bitbake -f -c install <recipe>".into(),
                description: "Re-run installation.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "install".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1642").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -f -c package <recipe>".into(),
            description: "Re-run package splitting.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1642").unwrap(),
                heading: "25.8 Packaging failure".into(),
                command: "bitbake -f -c package <recipe>".into(),
                description: "Re-run package splitting.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "package".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1645").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -f -c package_qa <recipe>".into(),
            description: "Re-run package QA.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1645").unwrap(),
                heading: "25.8 Packaging failure".into(),
                command: "bitbake -f -c package_qa <recipe>".into(),
                description: "Re-run package QA.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "package_qa".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1648").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -e <recipe> | grep '^FILES'".into(),
            description: "Inspect package assignments.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1648").unwrap(),
                heading: "25.8 Packaging failure".into(),
                command: "bitbake -e <recipe> | grep '^FILES'".into(),
                description: "Inspect package assignments.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1651").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -e <recipe> | grep '^PACKAGES='".into(),
            description: "Inspect generated packages.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1651").unwrap(),
                heading: "25.8 Packaging failure".into(),
                command: "bitbake -e <recipe> | grep '^PACKAGES='".into(),
                description: "Inspect generated packages.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1658").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -S printdiff <recipe>".into(),
            description: "Ask BitBake to compare task signatures.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1658").unwrap(),
                heading: "25.9 Unexpected rebuild".into(),
                command: "bitbake -S printdiff <recipe>".into(),
                description: "Ask BitBake to compare task signatures.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-S".into() },
                        RawArgument::Literal {
                            value: "printdiff".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawDumpSignatures,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1661").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -e <recipe> > recipe.env".into(),
            description: "Save the expanded environment for manual comparison.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1661").unwrap(),
                heading: "25.9 Unexpected rebuild".into(),
                command: "bitbake -e <recipe> > recipe.env".into(),
                description: "Save the expanded environment for manual comparison.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1670").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -f -c compile <recipe>".into(),
            description: "Force compilation without deleting sstate.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1670").unwrap(),
                heading: "25.10 Suspect stale state".into(),
                command: "bitbake -f -c compile <recipe>".into(),
                description: "Force compilation without deleting sstate.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1677").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake -c cleansstate <recipe>".into(),
            description: "Remove recipe work and local sstate.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1677").unwrap(),
                heading: "25.10 Suspect stale state".into(),
                command: "bitbake -c cleansstate <recipe>".into(),
                description: "Remove recipe work and local sstate.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "cleansstate".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Destructive,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-25-practical-debugging-workflows.l1684").unwrap(),
            category: RawCategoryId::new("section-25-practical-debugging-workflows").unwrap(),
            label: "bitbake <recipe>".into(),
            description: "Rebuild the recipe normally.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1684").unwrap(),
                heading: "25.10 Suspect stale state".into(),
                command: "bitbake <recipe>".into(),
                description: "Rebuild the recipe normally.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![RawArgument::Parameter {
                        parameter: RawParameterId::new("recipe").unwrap(),
                    }],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
