// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1363").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -c install <recipe>".into(),
            description: "Run installation into ${D}.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1363").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -c install <recipe>".into(),
                description: "Run installation into ${D}.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "install".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1366").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -c package <recipe>".into(),
            description: "Run package splitting.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1366").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -c package <recipe>".into(),
                description: "Run package splitting.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "package".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1369").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -c recipe_qa <recipe>".into(),
            description: "Run recipe metadata QA.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1369").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -c recipe_qa <recipe>".into(),
                description: "Run recipe metadata QA.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "recipe_qa".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1372").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -c package_qa <recipe>".into(),
            description: "Run package QA.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1372").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -c package_qa <recipe>".into(),
                description: "Run package QA.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "package_qa".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1375").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -c packagedata <recipe>".into(),
            description: "Write package metadata.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1375").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -c packagedata <recipe>".into(),
                description: "Write package metadata.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "packagedata".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1378").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^PACKAGES='".into(),
            description: "Show generated package names.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1378").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -e <recipe> | grep '^PACKAGES='".into(),
                description: "Show generated package names.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1381").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^FILES'".into(),
            description: "Inspect FILES assignments.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1381").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -e <recipe> | grep '^FILES'".into(),
                description: "Inspect FILES assignments.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1384").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^RDEPENDS'".into(),
            description: "Inspect runtime dependencies.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1384").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -e <recipe> | grep '^RDEPENDS'".into(),
                description: "Inspect runtime dependencies.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1387").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^D='".into(),
            description: "Show the install staging directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1387").unwrap(),
                heading: "22. Package debugging".into(),
                command: "bitbake -e <recipe> | grep '^D='".into(),
                description: "Show the install staging directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1390").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "find tmp/work -path \"*<recipe>*\" -name 'log.do_install*'".into(),
            description: "Find install logs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1390").unwrap(),
                heading: "22. Package debugging".into(),
                command: "find tmp/work -path \"*<recipe>*\" -name 'log.do_install*'".into(),
                description: "Find install logs.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1393").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "find tmp/work -path \"*<recipe>*\" -name 'log.do_package*'".into(),
            description: "Find package logs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1393").unwrap(),
                heading: "22. Package debugging".into(),
                command: "find tmp/work -path \"*<recipe>*\" -name 'log.do_package*'".into(),
                description: "Find package logs.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-22-package-debugging.l1396").unwrap(),
            category: RawCategoryId::new("section-22-package-debugging").unwrap(),
            label: "find tmp/work -path \"*<recipe>*\" -name 'log.do_package_qa*'".into(),
            description: "Find package QA logs.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1396").unwrap(),
                heading: "22. Package debugging".into(),
                command: "find tmp/work -path \"*<recipe>*\" -name 'log.do_package_qa*'".into(),
                description: "Find package QA logs.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::CompanionTool,
                reason: "Uses a companion tool or shell command; Raw Mode executes only structured BitBake argv.".into(),
            },
        },
    ]
}
