// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1281").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^WORKDIR='".into(),
            description: "Find the recipe's WORKDIR.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1281").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -e <recipe> | grep '^WORKDIR='".into(),
                description: "Find the recipe's WORKDIR.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1284").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^S='".into(),
            description: "Find its source tree.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1284").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -e <recipe> | grep '^S='".into(),
                description: "Find its source tree.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1287").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^B='".into(),
            description: "Find its build directory.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1287").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -e <recipe> | grep '^B='".into(),
                description: "Find its build directory.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1290").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -c configure <recipe>".into(),
            description: "Run only configuration.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1290").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -c configure <recipe>".into(),
                description: "Run only configuration.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "configure".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1293").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -f -c configure <recipe>".into(),
            description: "Force configuration to run.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1293").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -f -c configure <recipe>".into(),
                description: "Force configuration to run.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "configure".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1296").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -c compile <recipe>".into(),
            description: "Run only compilation.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1296").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -c compile <recipe>".into(),
                description: "Run only compilation.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1299").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -f -c compile <recipe>".into(),
            description: "Force compilation to run.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1299").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -f -c compile <recipe>".into(),
                description: "Force compilation to run.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1302").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -v -f -c compile <recipe>".into(),
            description: "Run compilation with shell tracing.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1302").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -v -f -c compile <recipe>".into(),
                description: "Run compilation with shell tracing.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-v".into() },
                        RawArgument::Literal { value: "-f".into() },
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "compile".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::BitBakeForceTask,
                            CapabilityId::BitBakeRawVerbose,
                        ],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1305").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -c devshell <recipe>".into(),
            description: "Enter the exact recipe cross-build environment.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1305").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -c devshell <recipe>".into(),
                description: "Enter the exact recipe cross-build environment.".into(),
            },
            parameters: vec![RawParameter {
                id: RawParameterId::new("recipe").unwrap(),
                label: "Recipe".into(),
                placeholder: "<recipe>".into(),
                kind: RawParameterKind::Recipe,
                presence: RawParameterPresence::Required,
            }],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                        RawArgument::Literal { value: "-c".into() },
                        RawArgument::Literal {
                            value: "devshell".into(),
                        },
                        RawArgument::Parameter {
                            parameter: RawParameterId::new("recipe").unwrap(),
                        },
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![
                            CapabilityId::BitBakeRawCli,
                            CapabilityId::BitBakeRawTaskExecution,
                            CapabilityId::DevShell,
                        ],
                    },
                    interaction: RawInteractionMode::InteractivePty,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1308").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^CC='".into(),
            description: "Find the compiler BitBake selected.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1308").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -e <recipe> | grep '^CC='".into(),
                description: "Find the compiler BitBake selected.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1311").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^CFLAGS='".into(),
            description: "Find CFLAGS.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1311").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -e <recipe> | grep '^CFLAGS='".into(),
                description: "Find CFLAGS.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
        RawCommand {
            id: RawCommandId::new("section-21-compile-configure-debugging.l1314").unwrap(),
            category: RawCategoryId::new("section-21-compile-configure-debugging").unwrap(),
            label: "bitbake -e <recipe> | grep '^CXXFLAGS='".into(),
            description: "Find CXXFLAGS.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l1314").unwrap(),
                heading: "21. Compile/configure debugging".into(),
                command: "bitbake -e <recipe> | grep '^CXXFLAGS='".into(),
                description: "Find CXXFLAGS.".into(),
            },
            parameters: vec![],
            execution: RawExecutionPolicy::ReferenceOnly {
                kind: RawReferenceKind::ShellPipeline,
                reason: "Requires a shell pipeline or redirection; Raw Mode never invokes a shell."
                    .into(),
            },
        },
    ]
}
