// @generated by scripts/generate-raw-catalog.py; do not edit by hand.
use crate::*;

pub(super) fn commands() -> Vec<RawCommand> {
    vec![
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0365").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake -c listtasks <recipe>".into(),
            description: "List every task defined for a recipe.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0365").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake -c listtasks <recipe>".into(),
                description: "List every task defined for a recipe.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Literal { value: "listtasks".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeTaskList],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Inspection,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0368").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake -c <task> <recipe>".into(),
            description: "Execute a specific task.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0368").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake -c <task> <recipe>".into(),
                description: "Execute a specific task.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0371").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake <recipe> -c <task>".into(),
            description: "Equivalent ordering commonly used by Yocto developers.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0371").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake <recipe> -c <task>".into(),
                description: "Equivalent ordering commonly used by Yocto developers.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0374").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake -f -c <task> <recipe>".into(),
            description: "Force a specific task to run.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0374").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake -f -c <task> <recipe>".into(),
                description: "Force a specific task to run.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0377").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake -v -c <task> <recipe>".into(),
            description: "Run a task and show verbose shell execution.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0377").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake -v -c <task> <recipe>".into(),
                description: "Run a task and show verbose shell execution.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-v".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeRawVerbose],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0380").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake -v -f -c <task> <recipe>".into(),
            description: "Force and trace a task.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0380").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake -v -f -c <task> <recipe>".into(),
                description: "Force and trace a task.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-v".into() },
                    RawArgument::Literal { value: "-f".into() },
                    RawArgument::Literal { value: "-c".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawTaskExecution, CapabilityId::BitBakeForceTask, CapabilityId::BitBakeRawVerbose],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
        RawCommand {
            id: RawCommandId::new("section-04-recipe-task-execution.l0383").unwrap(),
            category: RawCategoryId::new("section-04-recipe-task-execution").unwrap(),
            label: "bitbake -C <task> <recipe>".into(),
            description: "Invalidate a task stamp and rebuild the recipe normally from that point as dependencies require.".into(),
            reference: RawReference {
                id: RawReferenceId::new("wrynose-6-0.l0383").unwrap(),
                heading: "4. Recipe task execution".into(),
                command: "bitbake -C <task> <recipe>".into(),
                description: "Invalidate a task stamp and rebuild the recipe normally from that point as dependencies require.".into(),
            },
            parameters: vec![
                RawParameter { id: RawParameterId::new("task").unwrap(), label: "Task".into(), placeholder: "<task>".into(), kind: RawParameterKind::Task, presence: RawParameterPresence::Required },
                RawParameter { id: RawParameterId::new("recipe").unwrap(), label: "Recipe".into(), placeholder: "<recipe>".into(), kind: RawParameterKind::Recipe, presence: RawParameterPresence::Required }
            ],
            execution: RawExecutionPolicy::Executable {
                template: RawExecutableTemplate {
                    executable: RawExecutable::BitBake,
                    arguments: vec![
                    RawArgument::Literal { value: "-C".into() },
                    RawArgument::Parameter { parameter: RawParameterId::new("task").unwrap() },
                    RawArgument::Parameter { parameter: RawParameterId::new("recipe").unwrap() }
                    ],
                    capabilities: RawCapabilityRequirement::All {
                        capabilities: vec![CapabilityId::BitBakeRawCli, CapabilityId::BitBakeRawClearStamp],
                    },
                    interaction: RawInteractionMode::NoninteractiveJob,
                    safety: RawSafetyClass::Build,
                },
            },
        },
    ]
}
