//! Regression tests grouped around ux_dependency_graph_maps_typed_navigation_filter_topology_and_open_actions.
use super::*;

mod recipe_bitbake_action_maps_standard_and_forced_task_controls;
mod recipe_navigation_maps_files_logs_patches_and_devtool_routes;
mod ux_dependency_graph_maps_typed_navigation_filter_topology_and_open_actions;
mod ux_dependency_graph_mouse_click_selects_exact_projected_identity;

mod devtool_metadata_shortcut_requests_typed_status;

mod config_workspace_maps_search_selection_and_lazy_detail;

mod config_copy_shortcuts_are_typed;

mod config_source_picker_keys_are_modal_and_typed;

mod config_scope_shortcut_and_picker_keys_are_typed;

mod config_compare_shortcut_and_close_keys_are_typed;

mod config_edit_preview_shortcut_and_dialog_keys_are_typed;

mod config_edit_write_confirmation_is_modal_and_cancellable;

mod devwork_editor_routes_confirmation_and_workspace_editor_build_keys;

mod devtool_publish_update_routes_only_confirmation_keys;

mod devtool_publish_finish_routes_picker_and_confirmation_keys;

mod devtool_target_deploy_routes_entry_and_confirmation_keys;

mod devtool_target_reset_routes_only_destructive_confirmation_keys;

mod devtool_job_lifecycle_maps_runner_events_and_stays_independent_from_bitbake;

mod devtool_job_lifecycle_maps_start_failure_cancel_failure_cancel_and_loss;

mod recipe_qa_action_maps_capabilities_and_persists_terminal_job_outcomes;

mod images_workspace_image_action_maps_search_refresh_build_cancel_and_open_actions;
mod signature_workspace_maps_recipe_entry_picker_and_workspace_keys;

mod image_console_input_keeps_text_typing_separate_from_choice_navigation;

mod ux_rootfs_images_tabs_keyboard_and_scroll_map_to_typed_drilldown_actions;

mod udev_keys_select_sixth_tab_and_scroll_without_spawning;
