fn additional_global_metadata(command: CommandId) -> Option<GlobalMetadata> {
    Some(match command {
        CommandId::OpenInsights => navigation(
            "navigate.insights",
            "Open Insights",
            "Inspect build telemetry and resource history",
            &[],
            &["insights", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenBuildHistory => navigation(
            "navigate.build-history",
            "Open Build History",
            "Browse saved builds and historical outcomes",
            &[],
            &["buildhistory", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenSignatures => navigation(
            "navigate.signatures",
            "Open Signatures",
            "Inspect task signatures and rebuild differences",
            &[],
            &["signatures", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenLayerRelationships => navigation(
            "navigate.layer-relationships",
            "Open Layer Relationships",
            "Inspect layer dependencies and relationships",
            &[],
            &["layerrelationships", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenDevtoolWorkspace => navigation(
            "navigate.devtool",
            "Open Devtool Workspace",
            "Browse retained Devtool workspaces and jobs",
            &[],
            &["devtool", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenKernel => navigation(
            "navigate.kernel",
            "Open Kernel",
            "Inspect kernel configuration, device trees, and debug workflows",
            &[],
            &["kernel", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenFirmware => navigation(
            "navigate.firmware",
            "Open U-Boot / BIOS",
            "Inspect firmware configuration and source workflows",
            &[],
            &["firmware", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenBbmask => navigation(
            "navigate.bbmask",
            "Open BBMASK",
            "Inspect recipe exclusion patterns before editing",
            &[],
            &["bbmask", "navigate"],
            &[],
            50,
        ),
        CommandId::OpenCommandPalette => GlobalMetadata {
            menu_path: vec!["Workspace", "Command palette"],
            ..navigation(
                "navigate.command-palette",
                "Command palette",
                "Find and run an available command",
                &["commands"],
                &["command", "palette", "search"],
                &[],
                50,
            )
        },
        CommandId::Quit => GlobalMetadata {
            safety: OperatorActionSafety::ConfirmationRequired,
            menu_path: vec!["Workspace", "Quit"],
            ..navigation(
                "app.quit",
                "Quit",
                "Review the quit confirmation before exiting Yoctui",
                &["exit"],
                &["quit", "exit"],
                &[],
                0,
            )
        },
        _ => return None,
    })
}
