fn global_metadata(command: CommandId) -> GlobalMetadata {
    use OperatorActionHelpGroup as Group;
    use OperatorActionLocalRequirement as Local;
    use OperatorActionSafety as Safety;
    use OperatorActionScope as Scope;
    match command {
        CommandId::BuildImage => GlobalMetadata {
            id: "build.image",
            scope: Scope::Workspace(WorkspaceDestination::Images),
            menu_path: vec!["Build", "Build image"],
            label: "Build image",
            description: "Open image build options for the active machine",
            aliases: &["image build", "bitbake image"],
            keywords: &["build", "image", "machine", "bitbake"],
            bindings: &["B"],
            local_requirement: Local::WorkspaceLoaded,
            safety: Safety::ConfirmationRequired,
            footer_priority: 90,
            help_group: Group::Build,
        },
        CommandId::SelectImage => GlobalMetadata {
            id: "navigate.select-image",
            scope: Scope::Workspace(WorkspaceDestination::Images),
            menu_path: vec!["Navigate", "Select image"],
            label: "Select image",
            description: "Choose an image recipe discovered in active layers",
            aliases: &["image picker", "choose image"],
            keywords: &["navigate", "image", "recipe", "select"],
            bindings: &["i"],
            local_requirement: Local::ImageRecipeAvailable,
            safety: Safety::ReadOnly,
            footer_priority: 70,
            help_group: Group::Navigate,
        },
        CommandId::BuildSelectedRecipe => GlobalMetadata {
            id: "build.selected-recipe",
            scope: Scope::Workspace(WorkspaceDestination::Recipes),
            menu_path: vec!["Build", "Build selected recipe"],
            label: "Build selected recipe",
            description: "Confirm and build the selected recipe",
            aliases: &["recipe build", "bitbake recipe"],
            keywords: &["build", "recipe", "selected", "bitbake"],
            bindings: &["b"],
            local_requirement: Local::SelectedRecipe,
            safety: Safety::ConfirmationRequired,
            footer_priority: 90,
            help_group: Group::Build,
        },
        CommandId::EditBbmask => GlobalMetadata {
            id: "configure.bbmask",
            scope: Scope::Workspace(WorkspaceDestination::Configuration),
            menu_path: vec!["Workspace", "Configuration", "Edit BBMASK"],
            label: "Edit BBMASK",
            description: "Preview and save the effective BBMASK value",
            aliases: &["mask recipes", "configuration mask"],
            keywords: &["configure", "bbmask", "recipe", "mask"],
            bindings: &["x e"],
            local_requirement: Local::WorkspaceLoaded,
            safety: Safety::ConfirmationRequired,
            footer_priority: 55,
            help_group: Group::Configure,
        },
        CommandId::OpenDashboard => navigation(
            "navigate.dashboard",
            "Open Dashboard",
            "Show build status, task progress, and recent output",
            &["home", "overview"],
            &["dashboard", "home", "status", "overview"],
            &["Esc", "F4"],
            75,
        ),
        CommandId::OpenLayers => navigation(
            "navigate.layers",
            "Open Layers",
            "Browse active layer metadata and files",
            &["layer browser"],
            &["layers", "metadata", "files"],
            &["y", "F6"],
            65,
        ),
        CommandId::OpenRecipes => navigation(
            "navigate.recipes",
            "Open Recipes",
            "Browse recipes and typed recipe actions",
            &["recipe browser"],
            &["recipes", "metadata", "build"],
            &["r", "F7"],
            70,
        ),
        CommandId::OpenPackages => navigation(
            "navigate.packages",
            "Open Packages",
            "Inspect package inventory, metadata, and rootfs contents",
            &["pkgdata", "installed packages", "rootfs"],
            &["packages", "pkgdata", "rootfs", "contents"],
            &[],
            60,
        ),
        CommandId::OpenImages => navigation(
            "navigate.images",
            "Open Images",
            "Browse image recipes and artifacts",
            &["image browser"],
            &["images", "artifacts", "deploy"],
            &["i", "F8"],
            70,
        ),
        CommandId::OpenSdk => navigation(
            "navigate.sdk",
            "Open SDK",
            "Inspect SDK artifacts and toolchain workflows",
            &["toolchain", "populate sdk"],
            &["sdk", "toolchain", "populate", "artifacts"],
            &[],
            55,
        ),
        CommandId::OpenDependencies => navigation(
            "navigate.dependencies",
            "Open Dependencies",
            "Inspect dependency graphs, providers, and relationships",
            &["dependency graph", "providers"],
            &["dependencies", "graph", "providers", "relationships"],
            &[],
            55,
        ),
        CommandId::OpenTesting => navigation(
            "navigate.testing",
            "Open Testing",
            "Run and inspect Yocto test workflows and results",
            &["test results", "testimage", "oe-selftest"],
            &["testing", "testimage", "oe-selftest", "resulttool"],
            &[],
            55,
        ),
        CommandId::OpenSecurity => navigation(
            "navigate.security",
            "Open Security",
            "Inspect CVE, SPDX, and software-bill-of-materials workflows",
            &["cve", "spdx", "sbom"],
            &["security", "cve", "spdx", "sbom"],
            &[],
            55,
        ),
        CommandId::OpenQa => navigation(
            "navigate.qa",
            "Open QA",
            "Inspect quality checks and layer validation workflows",
            &["quality assurance", "yocto-check-layer"],
            &["qa", "quality", "checks", "yocto-check-layer"],
            &[],
            55,
        ),
        CommandId::OpenTasks => navigation(
            "navigate.tasks",
            "Open Tasks",
            "Inspect active and completed BitBake tasks",
            &["task monitor"],
            &["tasks", "jobs", "build", "progress"],
            &["t", "F2"],
            75,
        ),
        CommandId::OpenLogs => navigation(
            "navigate.logs",
            "Open Logs",
            "Inspect retained structured build logs",
            &["build output"],
            &["logs", "output", "build", "diagnostics"],
            &["l", "F5"],
            70,
        ),
        CommandId::OpenErrors => navigation(
            "navigate.errors",
            "Open Errors",
            "Inspect retained warnings and errors",
            &["diagnostics", "failures"],
            &["errors", "warnings", "failures", "diagnostics"],
            &["e"],
            70,
        ),
        CommandId::OpenConfiguration => navigation(
            "navigate.configuration",
            "Open Configuration",
            "Inspect effective BitBake variables and provenance",
            &["variables", "bitbake environment"],
            &["configuration", "variables", "provenance", "environment"],
            &["v"],
            60,
        ),
        CommandId::OpenRawMode => navigation(
            "navigate.raw-mode",
            "Open Raw Mode",
            "Inspect the structured BitBake command catalog",
            &["raw commands", "command workbench"],
            &["raw", "commands", "bitbake", "advanced"],
            &[],
            35,
        ),
        CommandId::OpenGitUi => {
            let mut metadata = navigation(
                "tools.gitui",
                "Open GitUI",
                "Review source diffs, stage changes, commit and synchronize in GitUI",
                &["git", "diff", "commit"],
                &["git", "source", "stage", "push", "fetch"],
                &[],
                65,
            );
            metadata.menu_path = vec!["Tools", "GitUI"];
            metadata.help_group = Group::Operate;
            metadata
        }
        CommandId::OpenTerminalSessions => navigation(
            "navigate.terminal-sessions",
            "Open Terminal Sessions",
            "Open the daemon-owned terminal session workbench",
            &["terminal", "shell", "pty", "devshell"],
            &["terminal", "shell", "pty", "session", "devshell"],
            &[],
            65,
        ),
        CommandId::OpenMaintenance => navigation(
            "navigate.maintenance",
            "Open Maintenance",
            "Inspect sstate, PR service, build history, and release maintenance",
            &["sstate", "prserv", "buildhistory"],
            &["maintenance", "sstate", "prserv", "buildhistory"],
            &[],
            45,
        ),
        CommandId::OpenBuildEnvironment => navigation(
            "navigate.build-environment",
            "Open Build Environment",
            "Configure and verify the active Poky build environment",
            &["workspace", "poky environment"],
            &["build", "environment", "poky", "workspace"],
            &[],
            60,
        ),
        CommandId::OpenCompatibility => navigation(
            "navigate.compatibility",
            "Open Compatibility",
            "Inspect connected environment identity and capability evidence",
            &["capabilities", "support"],
            &["compatibility", "capability", "environment", "support"],
            &[],
            40,
        ),
        CommandId::OpenSettings => navigation(
            "navigate.settings",
            "Open Settings",
            "Edit persistent visual and log preferences",
            &["preferences"],
            &["settings", "preferences", "theme", "logs"],
            &[],
            40,
        ),
        CommandId::ChooseTheme => GlobalMetadata {
            id: "view.choose-theme",
            scope: Scope::Global,
            menu_path: vec!["View", "Choose theme"],
            label: "Choose theme",
            description: "Preview and apply a named workbench palette",
            aliases: &["appearance", "colors"],
            keywords: &["theme", "appearance", "color", "palette"],
            bindings: &[],
            local_requirement: Local::None,
            safety: Safety::ReadOnly,
            footer_priority: 20,
            help_group: Group::General,
        },
        CommandId::FocusNavigator => focus_metadata(
            "view.focus-navigator",
            "Focus Navigator",
            "Move input focus directly to the Navigator pane",
        ),
        CommandId::FocusWorkspace => focus_metadata(
            "view.focus-workspace",
            "Focus Workspace",
            "Move input focus directly to the active Workspace pane",
        ),
        CommandId::FocusInspector => focus_metadata(
            "view.focus-inspector",
            "Focus Inspector",
            "Move input focus directly to the Inspector pane",
        ),
        CommandId::PreviousSubfocus => focus_metadata(
            "view.previous-subfocus",
            "Previous subfocus",
            "Move to the previous logical section in the focused pane",
        ),
        CommandId::NextSubfocus => focus_metadata(
            "view.next-subfocus",
            "Next subfocus",
            "Move to the next logical section in the focused pane",
        ),
        CommandId::TogglePaneZoom => focus_metadata(
            "view.toggle-pane-zoom",
            "Toggle pane zoom",
            "Zoom or restore the focused pane without changing its state",
        ),
        CommandId::ScrollFirst => navigation(
            "navigate.collection-first",
            "First row",
            "Move to the first retained row in the active collection",
            &["top", "start"],
            &["navigate", "scroll", "first", "top", "collection"],
            &["g g", "Home"],
            55,
        ),
        CommandId::ScrollLast => navigation(
            "navigate.collection-last",
            "Last row",
            "Move to the last retained row in the active collection",
            &["bottom", "end"],
            &["navigate", "scroll", "last", "bottom", "collection"],
            &["G", "End"],
            55,
        ),
        CommandId::OpenOnboarding => GlobalMetadata {
            id: "help.operator-guide",
            scope: Scope::Global,
            menu_path: vec!["Help", "Operator guide"],
            label: "Open operator guide",
            description: "Open the guided path through setup, inspection, build, and diagnostics",
            aliases: &["onboarding", "getting started", "first run"],
            keywords: &["guide", "onboarding", "tutorial", "workflow", "first run"],
            bindings: &[],
            local_requirement: Local::None,
            safety: Safety::ReadOnly,
            footer_priority: 95,
            help_group: Group::General,
        },
        CommandId::OpenHelp => GlobalMetadata {
            id: "help.open",
            scope: Scope::Global,
            menu_path: vec!["Help", "Open Help"],
            label: "Open Help",
            description: "Show global and contextual actions and shortcuts",
            aliases: &["shortcuts", "keys"],
            keywords: &["help", "shortcuts", "actions", "keys"],
            bindings: &["?", "F1"],
            local_requirement: Local::None,
            safety: Safety::ReadOnly,
            footer_priority: 100,
            help_group: Group::General,
        },
        CommandId::OpenAbout => GlobalMetadata {
            id: "help.about",
            scope: Scope::Global,
            menu_path: vec!["Help", "About Yoctui"],
            label: "About Yoctui",
            description: "Show the running version, source build SHA, and project purpose",
            aliases: &["version", "build", "sha"],
            keywords: &["about", "version", "build", "sha", "yoctui"],
            bindings: &[],
            local_requirement: Local::None,
            safety: Safety::ReadOnly,
            footer_priority: 20,
            help_group: Group::General,
        },
    }
}

fn focus_metadata(
    id: &'static str,
    label: &'static str,
    description: &'static str,
) -> GlobalMetadata {
    GlobalMetadata {
        id,
        scope: OperatorActionScope::Global,
        menu_path: vec!["View", label],
        label,
        description,
        aliases: &["pane focus", "zoom", "subfocus"],
        keywords: &["view", "pane", "focus", "zoom", "subfocus"],
        bindings: &[],
        local_requirement: OperatorActionLocalRequirement::None,
        safety: OperatorActionSafety::ReadOnly,
        footer_priority: 25,
        help_group: OperatorActionHelpGroup::General,
    }
}

fn navigation(
    id: &'static str,
    label: &'static str,
    description: &'static str,
    aliases: &'static [&'static str],
    keywords: &'static [&'static str],
    bindings: &'static [&'static str],
    footer_priority: u8,
) -> GlobalMetadata {
    GlobalMetadata {
        id,
        scope: OperatorActionScope::Global,
        menu_path: vec!["Navigate", label],
        label,
        description,
        aliases,
        keywords,
        bindings,
        local_requirement: OperatorActionLocalRequirement::None,
        safety: OperatorActionSafety::ReadOnly,
        footer_priority,
        help_group: OperatorActionHelpGroup::Navigate,
    }
}
