use super::*;

mod ux_throbber_phase_is_reducer_owned_and_terminal_states_never_animate;

mod ux_accessibility_reduced_motion_keeps_every_activity_lifecycle_textual_and_stable;

mod ux_progress_separates_build_parse_runqueue_resources_and_sstate;

mod ux_progress_preserves_unknown_totals_and_terminal_job_progress;
