//! Regression tests grouped around raw_mode_app_routes_only_the_selected_additional_field_to_shared_editor.
use super::*;

mod primary_contract;

mod raw_form_app_routes_selector_editor_fields_and_dialog_focus;

mod raw_navigation_routes_workspace_and_shared_focus_input;

mod raw_category_input_routes_bounded_browser_columns;

mod raw_job_client_confirmation_and_cancellation_remain_typed;

mod raw_pty_request_and_owner_round_trip_without_command_string_authority;

mod raw_output_keys_route_follow_search_scroll_cancel_and_attachment_as_typed_actions;

mod raw_execution_app_mechanically_round_trips_request_event_chunk_result_and_snapshot;

mod raw_history_app_installs_validated_records_without_recreating_execution_authority;

mod raw_execution_app_installs_reconnect_snapshots_and_rejects_stale_replacement;

mod ux_menu_keyboard_context_mouse_and_catalog_activation_share_typed_routes;

mod ux_menu_traps_input_over_recipe_editor_and_preserves_editor_state;

mod ux_focus_outward_escape_zoom_and_modal_input_are_typed_without_shortcut_theft;

mod ux_scroll_common_keys_map_to_typed_bounded_collection_actions;

mod ux_progress_backend_events_feed_distinct_typed_phase_projections;

mod ux_terminal_keys_are_modal_and_never_forward_control_actions;

mod devwork_terminal_dialog_keys_are_focus_trapped_and_recipe_routes_are_explicit;

mod dtc_compile_dialog_maps_only_typed_option_and_review_keys;

mod ux_onboarding_traps_input_and_routes_only_typed_guide_actions;
