//! Regression tests grouped around compatibility_dynamic_app_converts_installs_updates_and_invalidates_authority.
use super::*;

mod primary_contract;

mod compatibility_dynamic_app_rejects_unknown_wire_data_and_retains_newer_authority;

mod compatibility_decode_failure_is_not_repeated_for_unrelated_events;

mod compatibility_workspace_app_routes_local_effects_and_denies_unavailable_effects;

mod compatibility_ui_model_wire_lifecycle_reconciles_filter_search_and_selection;

mod compatibility_ui_inspector_keys_are_typed_modal_and_do_not_leak;

mod compatibility_ui_nav_actions_load_unload_and_reject_before_activation;

mod ux_action_catalog_drives_palette_metadata_search_and_workspace_projection;

mod ux_keymap_routes_scoped_defaults_custom_chords_and_traps_dialogs;

mod global_slash_search_routes_without_stealing_owned_text_input;

mod ux_keymap_preferences_capture_validate_reset_export_and_trap_focus;

mod compatibility_dynamic_app_actions_follow_installed_authority_and_runtime_gate;

mod compatibility_dynamic_app_dialogs_reject_confirm_and_revalidate_snapshot_changes;

mod compatibility_dynamic_app_parent_gate_enforces_one_runtime_authority;

mod mouse_routes_focus_and_scroll_semantically;
