#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {

    // Lifecycle and project state.
    SavedBuild(SavedBuildAction), OpenGitUi, GitUiDetected(Option<PathBuf>),
    SourceGitStatusUpdated(SourceGitStatus),
    SetBackgroundActivity { activity: BackgroundActivity, active: bool, },
    Tick, OpenOnboarding, DismissOnboarding,
    SelectOnboarding { delta: isize, },
    ActivateOnboardingStep, AdvanceOnboarding, SkipOnboardingStep,
    RestartOnboarding, OnboardingPersisted, OnboardingPersistenceFailed(String),
    ProjectProfileAbsent, ProjectProfileLoaded(ProjectProfile), ProjectProfileLoadFailed(String),
    PreviewProjectProfileGeneration(ProjectProfile),
    ConfirmProjectProfileGeneration { replace: bool, },
    ProjectProfileGenerated(ProjectProfile), ProjectProfileGenerationFailed(String),
    SelectProjectProfileItem { delta: isize, },
    ActivateProjectProfileItem, Open(Screen),

    // Platform workbenches.
    InspectKernel, KernelLoaded(PlatformInventory), KernelFailed(String),
    CycleKernelView, SetKernelView(PlatformView),
    SelectKernelFile { delta: isize, },
    LaunchKernelMenuconfig, OpenSelectedKernelFile, ExploreSelectedKernelRoot,
    CompileSelectedKernelDts, DecompileSelectedKernelDtb,
    SelectDtcCompileOption { delta: isize, },
    AdjustDtcCompileOption { delta: isize, },
    ConfirmDtcCompileOptions, CancelDtcCompileOptions, InspectFirmware,
    FirmwareLoaded(PlatformInventory), FirmwareFailed(String), CycleFirmwareView,
    SetFirmwareView(PlatformView),
    SelectFirmwareFile { delta: isize, },
    LaunchFirmwareMenuconfig, OpenSelectedFirmwareFile, ExploreSelectedFirmwareRoot,
    CompileSelectedFirmwareDts, DecompileSelectedFirmwareDtb,
    ShiftOverviewView { delta: isize, },
    SelectOverviewView(OverviewView), OpenRawFavorites,

    // Navigation and terminal interaction.
    SelectNavigator { delta: isize, },
    SelectNavigatorAt { index: usize, },
    ToggleNavigatorGroup { group: usize, },
    CollapseNavigatorGroup, ExpandNavigatorGroup,
    SelectPtySession { delta: isize, },
    SelectPtyPane { pane: PaneId, index: usize, },
    TerminalTakeControl, TerminalReleaseControl, TerminalCreateBuildShell,
    TerminalCreateSelectedDevshell, TerminalCreateSelectedMenuconfig, DetachedTerminalAvailabilityDetected(DetachedTerminalAvailability),
    SelectTerminalLaunchDestination { delta: isize, },
    ConfirmTerminalLaunch, CancelTerminalLaunch, TerminalEnterCopyMode,
    TerminalMoveCopyRow { delta: isize, },
    TerminalCopyViewport, TerminalBeginSearch, TerminalAppendSearch(char),
    TerminalBackspaceSearch, TerminalFinishSearch, TerminalClearSearch,
    TerminalStagePaste(String), TerminalConfirmPaste, TerminalBeginRename,
    TerminalAppendRename(char), TerminalBackspaceRename, TerminalConfirmRename,
    TerminalScroll { delta: isize, },
    TerminalBeginKill, TerminalConfirmKill, TerminalCancelMode,
    TerminalToggleHelp,
    ResizeFocusedPane { delta_per_mille: i16, },
    ActivateNavigator,
    CycleFocus { backwards: bool, },
    CyclePaneSubfocus { backwards: bool, },
    ResetPaneSubfocus, TogglePaneZoom,
    ScrollCurrent { to_end: bool, },
    Focus(FocusTarget),

    // Menus, settings, and compatibility.
    OpenCommandPalette, OpenGlobalSearch, OpenRecipeEditorWorkspaceSearch, BeginGlobalContentSearch,
    GlobalContentSearchLoaded { generation: u64, query: String, hits: Vec<GlobalSearchHit>, truncated: bool, searched_scopes: Vec<String>, },
    GlobalContentSearchFailed { generation: u64, query: String, message: String, },
    SelectCommandPalette { delta: isize, },
    AppendCommandPaletteQuery(char), BackspaceCommandPaletteQuery, ClearCommandPaletteQuery,
    ActivateCommandPalette, RestoreGlobalSearchResults, CloseCommandPalette, OpenApplicationMenu,
    OpenContextMenu,
    SelectMenuGroup { delta: isize, },
    SelectMenuItem { delta: isize, },
    AppendMenuPrefix(char), BackspaceMenuPrefix, CloseMenu,
    OpenYoctoUtility(YoctoUtilityCommand), SelectYoctoUtilityField { delta: isize, },
    CycleYoctoUtilityChoice { delta: isize, }, AppendYoctoUtilityField(char),
    BackspaceYoctoUtilityField, ClearYoctoUtilityField, ReviewYoctoUtility,
    CancelYoctoUtility,
    SelectSetting { delta: isize, },
    ChangeSelectedSetting { backwards: bool, },
    ResetPreferences, RetrySettingsPersistence, OpenKeymapPreferences,
    CloseKeymapPreferences,
    SelectKeymapPreference { delta: isize, },
    BeginKeymapPreferenceSearch, AppendKeymapPreferenceQuery(char), BackspaceKeymapPreferenceQuery,
    ClearKeymapPreferenceQuery, FinishKeymapPreferenceSearch, BeginKeymapCapture,
    AppendKeymapCapture(KeyStroke), BackspaceKeymapCapture, ConfirmKeymapCapture,
    CancelKeymapCapture, RemoveKeymapBinding, ResetKeymapBinding,
    ResetAllKeymapBindings, ExportEffectiveKeymap, SettingsPersisted,
    SettingsPersistenceFailed(String), SetCompatibilityFilter(CompatibilityUiFilter),
    SelectCompatibilityCapability { delta: isize, },
    BeginCompatibilitySearch, AppendCompatibilityQuery(char), BackspaceCompatibilityQuery,
    ClearCompatibilityQuery, FinishCompatibilitySearch, EditActivePopup(PopupEditorCommand),
    RawMode(RawModeAction),

    // Build environment and build launch.
    ConfigureBuildEnvironment(BuildEnvironmentProfile), OpenBuildEnvironmentCloneEditor, ToggleBuildEnvironmentCloneEditor,
    AppendBuildEnvironmentCloneEditor(char), BackspaceBuildEnvironmentCloneEditor, ReviewBuildEnvironmentClone,
    ConfirmBuildEnvironmentClone, CancelBuildEnvironmentClone, OpenBuildEnvironmentEditor,
    EnvironmentSetup(EnvironmentSetupAction), ToggleBuildEnvironmentEditor, AppendBuildEnvironmentEditor(char),
    BackspaceBuildEnvironmentEditor, ApplyBuildEnvironmentEditor, CloseBuildEnvironmentEditor,
    BeginBuildEnvironmentEdit, OpenThemePicker,
    SelectTheme { delta: isize, },
    ApplySelectedTheme, CloseThemePicker,
    SelectBuildEnvironmentField { delta: isize, },
    AppendBuildEnvironmentField(char), BackspaceBuildEnvironmentField, FinishBuildEnvironmentEdit,
    CancelBuildEnvironmentEdit, ApplyBuildEnvironmentProfile, BeginBuildEnvironmentVerification,
    BuildEnvironmentVerified { generation: u64, },
    BuildEnvironmentVerificationFailed { generation: u64, message: String, },
    OpenBuildOptions, CloseBuildOptions, OpenImagePicker(Vec<String>),
    OpenImageBuildPicker(Vec<String>), OpenRecipePicker(RecipePickerPurpose),
    SelectImage { delta: isize, },
    ConfirmImagePicker, CancelImagePicker, BeginCurrentImageBuild,
    SelectRecipePicker { delta: isize, }, ConfirmRecipePicker, CancelRecipePicker,

    // Image, root filesystem, and package workflows.
    BeginImageArtifactInventory, RefreshImageArtifactInventory, CancelImageArtifactOperation,
    ImageArtifactInventoryLoaded { request: ImageArtifactRequest, inventory: ImageArtifactInventory, },
    ImageArtifactInventoryPartial { request: ImageArtifactRequest, inventory: ImageArtifactInventory, limitations: Vec<String>, },
    ImageArtifactInventoryFailed { request: ImageArtifactRequest, message: String, },
    SelectImageArtifact { delta: isize, },
    BeginImageArtifactSearch, AppendImageArtifactQuery(char), BackspaceImageArtifactQuery,
    ClearImageArtifactQuery, FinishImageArtifactSearch, BeginSelectedImageArtifactBuild,
    OpenSelectedImageArtifact, OpenSelectedImageArtifactAssociation(ImageArtifactAssociation), BeginSelectedRootfsComposition,
    ShiftImagesView { delta: isize, },
    RefreshRootfsComposition,
    RootfsCompositionLoaded { request: RootfsCompositionRequest, composition: RootfsComposition, },
    RootfsCompositionPartial { request: RootfsCompositionRequest, composition: RootfsComposition, limitations: Vec<String>, },
    RootfsCompositionUnavailable { request: RootfsCompositionRequest, reason: String, },
    RootfsCompositionFailed { request: RootfsCompositionRequest, message: String, },
    SelectRootfsGroup { delta: isize, },
    SelectRootfsPackage { delta: isize, },
    SelectRootfsEntry { delta: isize, },
    SelectRootfsSystemdService { delta: isize, },
    SelectRootfsDbusService { delta: isize, },
    SelectRootfsUdevRule { delta: isize, },
    ScrollRootfsUdevPreview { delta: isize, },
    BrowseRootfsFilesystem, EditSelectedRootfsSystemFile, BeginSdkBuild(SdkBuildAction),
    ConfirmSdkBuild, CancelSdkBuild, BeginSdkArtifactInventory,
    RefreshSdkArtifactInventory,
    SdkArtifactInventoryLoaded { request: SdkArtifactInventoryRequest, artifacts: Vec<SdkArtifact>, limitations: Vec<String>, },
    SdkArtifactInventoryFailed { request: SdkArtifactInventoryRequest, message: String, },
    SelectSdkArtifact { delta: isize, },
    BeginSdkArtifactSearch, AppendSdkArtifactQuery(char), BackspaceSdkArtifactQuery,
    ClearSdkArtifactQuery, FinishSdkArtifactSearch, OpenSelectedSdkArtifact,
    SdkToolCapabilityLoaded(SdkToolCapability), BeginSelectedSdkPublish, ToggleSdkPublishTomlEditor,
    AppendSdkPublishTomlEditor(char), BackspaceSdkPublishTomlEditor, AppendSdkPublishDestination(char),
    BackspaceSdkPublishDestination, PreviewSdkPublish, CancelSdkPublish,
    CancelSdkPublishPreview, ConfirmSdkPublish, BeginSdkNative,
    ToggleSdkNativeTomlEditor, AppendSdkNativeTomlEditor(char), BackspaceSdkNativeTomlEditor,
    UpdateSdkNativeDraft(SdkNativeDraft),
    SelectSdkNativeField { delta: isize, },
    ActivateSdkNativeField, CycleSdkNativeMode, AppendSdkNativeField(char),
    BackspaceSdkNativeField, FinishSdkNativeFieldEdit, PreviewSdkNative,
    CancelSdkNative, CancelSdkNativePreview, ConfirmSdkNative,
    SdkSessionStarting { id: SdkSessionId, started_at: SystemTime, },
    SdkSessionRunning { id: SdkSessionId, },
    AppendSdkSessionOutput { id: SdkSessionId, stream: SdkOutputStream, line: String, truncated: bool, timestamp: SystemTime, },
    CompleteSdkSession { id: SdkSessionId, exit_code: i32, artifacts: Vec<PathBuf>, finished_at: SystemTime, },
    FailSdkSession { id: SdkSessionId, message: String, exit_code: Option<i32>, finished_at: SystemTime, },
    LoseSdkSession { id: SdkSessionId, message: String, finished_at: SystemTime, },
    BeginActiveSdkSessionCancellation, ConfirmSdkSessionCancellation, CancelSdkSessionCancellation,
    RejectSdkSessionCancellation { id: SdkSessionId, message: String, },
    CancelSdkSession { id: SdkSessionId, exit_code: Option<i32>, finished_at: SystemTime, },

    // Test workflows.
    InspectTestCapability, TestCapabilityLoaded(TestCapability),
    SelectTestFamily { delta: isize, },
    BeginSelectedTestLaunch, ToggleTestLaunchTomlEditor, AppendTestLaunchTomlEditor(char),
    BackspaceTestLaunchTomlEditor, UpdateTestLaunchDraft(TestLaunchDraft),
    SelectTestLaunchField { delta: isize, },
    ActivateTestLaunchField, AppendTestLaunchField(char), BackspaceTestLaunchField,
    FinishTestLaunchFieldEdit, PreviewTestLaunch, CancelTestLaunch,
    CancelTestLaunchPreview, ConfirmTestLaunch,
    AttachTestBuildSession { id: TestSessionId, background_job_id: BackgroundJobId, },
    TestSessionStarting { id: TestSessionId, started_at: SystemTime, },
    TestSessionRunning { id: TestSessionId, },
    AppendTestSessionOutput { id: TestSessionId, stream: TestOutputStream, line: String, truncated: bool, timestamp: SystemTime, },
    CompleteTestSession { id: TestSessionId, exit_code: i32, result_paths: Vec<PathBuf>, finished_at: SystemTime, },
    FailTestSession { id: TestSessionId, message: String, exit_code: Option<i32>, finished_at: SystemTime, },
    TimeoutTestSession { id: TestSessionId, forced: bool, exit_code: Option<i32>, finished_at: SystemTime, },
    LoseTestSession { id: TestSessionId, message: String, finished_at: SystemTime, },
    BeginActiveTestSessionCancellation, ConfirmTestSessionCancellation, CancelTestSessionCancellation,
    RejectTestSessionCancellation { id: TestSessionId, message: String, },
    CancelTestSession { id: TestSessionId, exit_code: Option<i32>, finished_at: SystemTime, },
    InspectResultToolCapability, ResultToolCapabilityLoaded(ResultToolCapability), CycleTestView,
    SelectTestView(TestWorkspaceView), BeginTestResultImport, ToggleTestResultImportTomlEditor,
    AppendTestResultImportTomlEditor(char), BackspaceTestResultImportTomlEditor, AppendTestResultImport(char),
    BackspaceTestResultImport, ConfirmTestResultImport, CancelTestResultImport,
    RefreshTestResults,
    TestResultsLoaded { request: TestResultImportRequest, records: Vec<TestResultRecord>, limitations: Vec<String>, },
    TestResultsFailed { request: TestResultImportRequest, message: String, },
    TestResultsCancelled { request: TestResultImportRequest, },
    TestResultsTimedOut { request: TestResultImportRequest, },
    TestResultsLost { request: TestResultImportRequest, message: String, },
    SelectTestResult { delta: isize, },
    BeginTestResultSearch, AppendTestResultQuery(char), BackspaceTestResultQuery,
    ClearTestResultQuery, FinishTestResultSearch, OpenSelectedTestResult,
    DrillIntoSelectedTestResult, LeaveTestResultCases,
    SelectTestCase { delta: isize, },
    OpenSelectedTestCaseLog, BeginTestComparison, ToggleTestComparisonTomlEditor,
    AppendTestComparisonTomlEditor(char), BackspaceTestComparisonTomlEditor,
    SelectTestComparisonChoice { delta: isize, },
    CycleTestComparisonField, ActivateTestComparisonChoice, PreviewTestComparison,
    CancelTestComparison, CancelTestComparisonPreview, ConfirmTestComparison,
    TestComparisonLoaded { request: TestComparisonRequest, comparison: TestComparison, limitations: Vec<String>, },
    TestComparisonFailed { request: TestComparisonRequest, message: String, },
    TestComparisonCancelled { request: TestComparisonRequest, },
    TestComparisonTimedOut { request: TestComparisonRequest, },
    TestComparisonLost { request: TestComparisonRequest, message: String, },
    SelectTestComparisonTransition { delta: isize, },
    OpenSelectedTestTransitionLog, BeginTestJunitExport, ToggleTestJunitTomlEditor,
    AppendTestJunitTomlEditor(char), BackspaceTestJunitTomlEditor, MoveTestJunitTomlEditorLeft,
    MoveTestJunitTomlEditorRight, MoveTestJunitTomlEditorUp, MoveTestJunitTomlEditorDown,
    MoveTestJunitTomlEditorHome, MoveTestJunitTomlEditorEnd, SelectTestJunitDestination,
    CopyTestJunitTomlEditor, PasteTestJunitTomlEditor, AppendTestJunitDestination(char),
    BackspaceTestJunitDestination, PreviewTestJunitExport, CancelTestJunitExport,
    TestJunitDestinationInspected { result: TestResultIdentity, inspection: TestJunitDestinationInspection, },
    CancelTestJunitExportPreview, ConfirmTestJunitExport,
    TestJunitExportSucceeded { request: TestJunitExportRequest, },
    TestJunitExportFailed { request: TestJunitExportRequest, message: String, },
    TestJunitExportCancelled { request: TestJunitExportRequest, },
    TestJunitExportTimedOut { request: TestJunitExportRequest, },
    TestJunitExportLost { request: TestJunitExportRequest, message: String, },

    // Security workflows.
    Security(SecurityAction),

    // QA workflows.
    Qa(QaAction),

    // Maintenance workflows.
    Maintenance(MaintenanceAction),

    // QEMU and WIC workflows.
    InspectQemuCapability, QemuCapabilityLoaded(QemuCapability), SshClientCapabilityDetected(SshClientCapability),
    BeginSelectedImageConsole,
    SelectImageConsoleField { delta: isize, },
    CycleImageConsoleChoice { backwards: bool, },
    AppendImageConsoleField(char), BackspaceImageConsoleField, ConfirmImageConsole,
    CancelImageConsole, BeginSelectedQemuLaunch, UpdateQemuLaunchDraft(QemuLaunchDraft),
    SelectQemuLaunchField { delta: isize, },
    ActivateQemuLaunchField,
    CycleQemuLaunchChoice { backwards: bool, },
    AppendQemuLaunchField(char), BackspaceQemuLaunchField, FinishQemuLaunchFieldEdit,
    PreviewQemuLaunch, CancelQemuLaunch, CancelQemuLaunchPreview,
    ConfirmQemuLaunch, ConfirmQemuLaunchInTerminal,
    QemuSessionStarting { id: QemuSessionId, started_at: SystemTime, },
    QemuSessionRunning { id: QemuSessionId, },
    AppendQemuSessionOutput { id: QemuSessionId, stream: QemuOutputStream, line: String, truncated: bool, timestamp: SystemTime, },
    CompleteQemuSession { id: QemuSessionId, exit_code: i32, finished_at: SystemTime, },
    FailQemuSession { id: QemuSessionId, message: String, exit_code: Option<i32>, finished_at: SystemTime, },
    LoseQemuSession { id: QemuSessionId, message: String, finished_at: SystemTime, },
    BeginQemuSessionCancellation { id: QemuSessionId, },
    BeginActiveQemuSessionCancellation, ConfirmQemuSessionCancellation, CancelQemuSessionCancellation,
    RejectQemuSessionCancellation { id: QemuSessionId, message: String, },
    CancelQemuSession { id: QemuSessionId, exit_code: Option<i32>, finished_at: SystemTime, },
    InspectWicCapability, WicCapabilityLoaded(WicCapability), BeginSelectedWicCreate,
    ToggleWicCreateTomlEditor, AppendWicCreateTomlEditor(char), BackspaceWicCreateTomlEditor,
    SelectWicCreateField { delta: isize, },
    ActivateWicCreateField,
    CycleWicCreateChoice { backwards: bool, },
    AppendWicCreateField(char), BackspaceWicCreateField, FinishWicCreateFieldEdit,
    PreviewWicCreate, CancelWicCreate, CancelWicCreatePreview,
    ConfirmWicCreate,
    SelectWicOutput { delta: isize, },
    OpenSelectedWicOutput, BeginActiveWicSessionCancellation, BeginActiveImageRuntimeCancellation,
    CancelWicSessionCancellation, BeginWicOutputInventory(WicOutputInventoryRequest),
    WicOutputInventoryLoaded { request: WicOutputInventoryRequest, outputs: Vec<WicOutput>, limitations: Vec<String>, },
    WicOutputInventoryFailed { request: WicOutputInventoryRequest, message: String, },
    BeginWicDeviceInventory(WicDeviceInventoryRequest),
    WicDeviceInventoryLoaded { request: WicDeviceInventoryRequest, devices: Vec<WicDevice>, limitations: Vec<String>, },
    WicDeviceInventoryFailed { request: WicDeviceInventoryRequest, message: String, },
    BeginSelectedWicDeviceWrite,
    SelectWicDevice { delta: isize, },
    ConfirmWicDeviceSelection, CancelWicDevicePicker, AppendWicWritePhrase(char),
    BackspaceWicWritePhrase, PreviewWicDeviceWrite, CancelWicWritePhrase,
    ConfirmWicDeviceWrite, CancelWicWritePreview, StartConfirmedWicCreate(WicCreatePreview),
    WicSessionStarting { id: WicSessionId, started_at: SystemTime, },
    WicSessionRunning { id: WicSessionId, },
    AppendWicSessionOutput { id: WicSessionId, stream: WicOutputStream, line: String, truncated: bool, timestamp: SystemTime, },
    CompleteWicSession { id: WicSessionId, exit_code: i32, outputs: Vec<WicOutput>, limitations: Vec<String>, finished_at: SystemTime, },
    FailWicSession { id: WicSessionId, message: String, exit_code: Option<i32>, finished_at: SystemTime, },
    LoseWicSession { id: WicSessionId, message: String, finished_at: SystemTime, },
    ConfirmWicSessionCancellation { id: WicSessionId, acknowledge_incomplete_device: bool, },
    RejectWicSessionCancellation { id: WicSessionId, message: String, },
    CancelWicSession { id: WicSessionId, exit_code: Option<i32>, finished_at: SystemTime, },
    BeginBuildTargetEdit, ToggleBuildTargetEdit, BeginBuildTargetTask(Option<String>),
    AppendBuildTarget(char), BackspaceBuildTarget, ConfirmBuildTarget,
    CancelBuildTargetEdit, Start(BuildRequest), QueueBackgroundJob(BackgroundJobSpec),
    StartBackgroundJob { id: BackgroundJobId, started_at: SystemTime, },
    RunBackgroundJob { id: BackgroundJobId, },
    UpdateBackgroundJobProgress { id: BackgroundJobId, progress: BackgroundJobProgress, },
    AppendBackgroundJobOutput { id: BackgroundJobId, entry: BackgroundJobOutputEntry, },
    RequestBackgroundJobCancellation { id: BackgroundJobId, },
    RejectBackgroundJobCancellation { id: BackgroundJobId, },
    SucceedBackgroundJob { id: BackgroundJobId, result: BackgroundJobResult, finished_at: SystemTime, },
    FailBackgroundJob { id: BackgroundJobId, error: BackgroundJobError, finished_at: SystemTime, },
    CancelBackgroundJob { id: BackgroundJobId, finished_at: SystemTime, },
    LoseBackgroundJob { id: BackgroundJobId, error: BackgroundJobError, finished_at: SystemTime, },
    BuildRequested { target: Option<String>, },
    BuildStarted, SstateSummary(SstateSummary), TaskStats(TaskStats),
    ParseProgress { current: Option<u64>, total: Option<u64>, },
    TaskStarted(TaskInfo), TaskQueued(TaskInfo),
    TaskProgress { id: TaskId, progress: Option<u8>, },
    TaskCompleted { id: TaskId, success: bool, },
    TaskEvents(Vec<TaskEvent>),
    ScrollBuildTasks { delta: isize, },
    CycleTaskStateFilter, CycleTaskFilterField, BeginTaskFilterEdit,
    AppendTaskFilter(char), BackspaceTaskFilter, FinishTaskFilterEdit,
    CycleTaskDurationFilter, Log(LogEntry), Logs(Vec<LogEntry>),
    BuildCompleted { success: bool, exit_code: Option<i32>, },
    BuildAuthorityLost { message: String, },
    BuildCancelled { exit_code: Option<i32>, },
    BuildCancellationRejected(String), DismissBuildCompletion, OpenBuildCompletionErrors,
    SelectBuildHistory { delta: isize, },
    Cancel, ConfirmBuildCancellation, CancelBuildCancellation,
    CycleLogWorkspaceView, InternalLog(InternalLogRecord), InternalLogIngressDropped(usize),
    ToggleInternalLogFollow,
    ScrollInternalLogs { delta: isize, },
    BeginInternalLogSearch, AppendInternalLogQuery(char), BackspaceInternalLogQuery,
    ClearInternalLogQuery, FinishInternalLogSearch, CycleInternalLogLevelFilter,
    CycleInternalLogTargetFilter, ClearInternalLogs, ExportInternalLogs,
    ToggleLogFollow, ToggleLogWrap, CycleLogSeverity,
    ScrollLogs { delta: isize, },
    BeginLogSearch, AppendLogQuery(char), BackspaceLogQuery,
    ClearLogQuery, FinishLogSearch, NextLogMatch,
    PreviousLogMatch,
    ScrollLogsHorizontally { delta: isize, },
    CycleLogRecipeFilter, CycleLogTaskFilter, CycleLogBuildFilter,
    CycleLogSourceFilter, CycleLogTimeRange, ToggleSelectedLogBookmark,
    NextLogBookmark, PreviousLogBookmark, OpenSelectedLogSource,
    CopySelectedLog, ExportFilteredLogs,
    SelectError { delta: isize, },
    JumpToSelectedError, OpenSelectedErrorSource,

    // Recipe, task, dependency, and signature workflows.
    SelectRecipe { delta: isize, },
    ScrollRecipePreview { delta: isize, },
    BeginSelectedRecipeBuild, BeginSelectedRecipeClean, BeginSelectedRecipeMenuConfig,
    BeginSelectedRecipeCleanState, BeginSelectedRecipeDevshell, BeginSelectedRecipeDevtoolWorkspaceShell,
    BeginSelectedRecipeDevtoolGitUi,
    BeginSelectedRecipeDevtoolEditRecipe, BeginSelectedRecipeDiffconfig, BeginSelectedRecipeDiffsigs,
    BeginSelectedRecipeSignatures, BeginSelectedRecipeCveCheck, BeginSelectedRecipeSpdx,
    BeginSelectedRecipeForceTask,
    BeginSelectedRecipeTask { task: Option<String>, force: bool, },
    SelectRecipeTask { delta: isize, },
    PreviewSelectedRecipeTask, CancelRecipeTaskPicker,
    SelectSignatureTask { delta: isize, },
    ConfirmSignatureTask, CancelSignatureTaskPicker, OpenSelectedRecipeProvider,
    BeginSelectedRecipeTaskLog,
    SelectRecipeTaskLog { delta: isize, },
    OpenSelectedRecipeTaskLog, CancelRecipeTaskLogPicker, BeginSelectedRecipePatchReview,
    SelectRecipePatch { delta: isize, },
    OpenSelectedRecipePatch, CancelRecipePatchPicker, BeginSelectedRecipeDevtoolModify,
    ConfirmDevtoolModify, CancelDevtoolModify, BeginSelectedRecipeDevtoolStatus,
    DevtoolStatusLoaded(DevtoolStatus), BeginSelectedRecipeDevtoolReset, BeginSelectedRecipeDevtoolUpdateRecipe,
    BeginSelectedRecipeDevtoolPatch,
    BeginSelectedRecipeDevtoolFinish, BeginSelectedRecipeDevtoolDeploy,
    BeginSelectedRecipeDevtoolUndeploy, BeginSelectedRecipeDevtoolUpgrade,
    BeginSelectedRecipeDependencies,
    BeginDependencyGraph { root: DependencyNodeId, },
    DependencyGraphLoaded(DependencyGraph),
    DependencyGraphPartial { graph: DependencyGraph, limitations: Vec<String>, },
    DependencyGraphFailed { root: DependencyNodeId, message: String, },
    SelectDependencyGraphNode { delta: isize, },
    SelectDependencyGraphNodeAt { identity: DependencyNodeId, },
    ToggleDependencyGraphReverse, CollapseSelectedDependencyGraphNode, ExpandSelectedDependencyGraphNode,
    ToggleSelectedDependencyGraphNode, BeginDependencyGraphSearch, AppendDependencyGraphQuery(char),
    BackspaceDependencyGraphQuery, ClearDependencyGraphQuery, FinishDependencyGraphSearch,
    RefreshDependencyGraph, OpenSelectedDependencyRecipe, OpenSelectedDependencyProvider,
    OpenSelectedDependencyTaskLog, BeginSignatureDump(SignatureTarget), RefreshSignatureDump,
    LeaveSignatureWorkspace, OpenSignatureProvider,
    SignatureDumpLoaded { target: SignatureTarget, records: Vec<SignatureRecord>, },
    SignatureDumpPartial { target: SignatureTarget, records: Vec<SignatureRecord>, limitations: Vec<String>, },
    SignatureDumpFailed { target: SignatureTarget, message: String, },
    SelectSignatureRecord { delta: isize, },
    SetSelectedSignatureComparisonSide(SignatureComparisonSide), BeginSignatureComparison,
    SignatureComparisonLoaded { request: SignatureComparisonRequest, differences: Vec<SignatureDifference>, },
    SignatureComparisonPartial { request: SignatureComparisonRequest, differences: Vec<SignatureDifference>, limitations: Vec<String>, },
    SignatureComparisonFailed { request: SignatureComparisonRequest, message: String, },
    BeginPackageInventory, RefreshPackageInventory, CancelPackageOperation,
    PackageInventoryLoaded { request: PackageInventoryRequest, packages: Vec<PackageSummary>, },
    PackageInventoryPartial { request: PackageInventoryRequest, packages: Vec<PackageSummary>, limitations: Vec<String>, },
    PackageInventoryFailed { request: PackageInventoryRequest, message: String, },
    SelectPackage { delta: isize, },
    BeginPackageSearch, AppendPackageQuery(char), BackspacePackageQuery,
    ClearPackageQuery, FinishPackageSearch, BeginSelectedPackageDetail,
    PackageDetailLoaded { request: PackageDetailRequest, detail: PackageDetail, },
    PackageDetailPartial { request: PackageDetailRequest, detail: PackageDetail, limitations: Vec<String>, },
    PackageDetailFailed { request: PackageDetailRequest, message: String, },
    OpenPackageDependency { identity: PackageIdentity, reverse: bool, },
    TogglePackageDependencyKind,
    SelectPackageDependency { delta: isize, },
    OpenSelectedPackageDependency, BackPackageNavigation, OpenSelectedPackageRecipe,
    OpenSelectedPackageProvider, BeginSelectedRecipeMetadata, RecipeMetadataLoaded(RecipeMetadata),
    RecipeMetadataFailed { recipe: String, message: String, },
    DependenciesLoaded(RecipeDependencies),
    SelectDependency { delta: isize, },
    OpenSelectedDependency,
    OpenRecipeEditor { recipe: String, root: PathBuf, files: Vec<PathBuf>, },
    SelectRecipeEditorFile { delta: isize, },
    LoadRecipeEditorContent(String), LoadRecipeEditorExternalContent(String), FocusRecipeEditor(RecipeEditorFocus),
    EditRecipeEditor(PopupEditorCommand), BeginRecipeEditorSearch, AppendRecipeEditorSearch(char),
    BackspaceRecipeEditorSearch, FinishRecipeEditorSearch,
    NextRecipeEditorMatch { backwards: bool, },
    ToggleRecipeEditorEditing, OpenRecipeEditorExternal, AppendRecipeEditor(char),
    BackspaceRecipeEditor, SaveRecipeEditor, RecipeEditorSaved,
    BeginRecipeEditorBuild, CloseRecipeEditor, ConfirmRecipeTask,
    CancelRecipeTask, ConfirmDevtoolReset, CancelDevtoolReset,
    ConfirmDevtoolUpdateRecipe, CancelDevtoolUpdateRecipe,
    SelectDevtoolPatchLayer { delta: isize }, PreviewDevtoolPatch, CancelDevtoolPatch,
    ConfirmDevtoolPatch, CancelDevtoolPatchConfirmation,
    SelectDevtoolFinishLayer { delta: isize, },
    PreviewDevtoolFinish, CancelDevtoolFinish, ConfirmDevtoolFinish,
    CancelDevtoolFinishConfirmation, AppendDevtoolDeployTarget(char), BackspaceDevtoolDeployTarget,
    PreviewDevtoolDeploy, CancelDevtoolDeploy, ConfirmDevtoolDeploy,
    CancelDevtoolDeployConfirmation,
    AppendDevtoolUndeployTarget(char), BackspaceDevtoolUndeployTarget,
    PreviewDevtoolUndeploy, CancelDevtoolUndeploy, ConfirmDevtoolUndeploy,
    CancelDevtoolUndeployConfirmation, ConfirmDevtoolUpgrade, CancelDevtoolUpgrade,
    SelectLayer { delta: isize, },
    OpenSelectedLayer, BeginSelectedLayerWorkspaceEditor, BeginSelectedLayerBrowser,
    LoadLayerBrowserDirectory { layer: String, root: PathBuf, directory: PathBuf, entries: Vec<LayerBrowserEntry>, },
    SelectLayerBrowserEntry { delta: isize, },
    LayerBrowserExpand, LayerBrowserEnter, LayerBrowserUp,
    CloseLayerBrowser, RefreshLayerBrowser, ToggleLayerBrowserHidden,
    SetLayerInspectorMode(LayerInspectorMode),
    ScrollLayerBrowserPreview { delta: isize, },
    FocusLayerBrowserTree,
    LoadLayerBrowserPreview { path: PathBuf, content: String, kind: PreviewKind, truncated: bool, },
    EditSelectedLayerBrowserFile, BeginLayerRelationships, LayerRelationshipsLoaded(LayerRelationships),
    SelectConfigVariable { delta: isize, },
    BeginSelectedConfigDetail, CopySelectedConfigEffective, CopySelectedConfigUnexpanded,
    SelectConfigSource { delta: isize, },
    OpenSelectedConfigSourceChoice, CancelConfigSourcePicker, OpenConfigScopePicker,
    SelectConfigScope { delta: isize, },
    ConfirmConfigScope, CancelConfigScopePicker, OpenConfigComparison,
    CloseConfigComparison, BeginConfigEdit, ToggleConfigEdit,
    AppendConfigEdit(char), BackspaceConfigEdit, PreviewConfigEdit,
    CancelConfigEdit, ConfirmConfigEdit, CancelConfigEditConfirmation,
    ConfigEditWriteSucceeded { identity: VariableIdentity, },
    ConfigEditWriteFailed { identity: VariableIdentity, message: String, },
    ConfigEditRefreshSucceeded { identity: VariableIdentity, },
    ConfigEditRefreshFailed { identity: VariableIdentity, message: String, },
    VariableDetailFailed { identity: VariableIdentity, message: String, },
    OpenSelectedConfigSource, BeginBbmaskEdit, ToggleBbmaskEdit,
    AppendBbmask(char), BackspaceBbmask, PreviewBbmaskEdit,
    CancelBbmaskEdit, ConfirmBbmaskWrite, CancelBbmaskWrite,
    BeginMetadataSearch, AppendMetadataQuery(char), BackspaceMetadataQuery,
    ClearMetadataQuery, FinishMetadataSearch,

    // Notifications, loading, and failures.
    Notify(String), ActivateNotification, DismissNotification,
    Quit, ConfirmQuit, CancelQuit,
    WorkspaceLoaded(Workspace), RecipesLoaded(Vec<Recipe>), LayersLoaded(Vec<Layer>),
    VariableLoaded(VariableDetail),
    RecipeSourcesLoaded { recipe: String, paths: Vec<PathBuf>, },
    HostTelemetryUpdated(HostTelemetry), Failure(AppError),
}
