//! Regression tests grouped around next_generation_navigator_mouse_and_keyboard_share_typed_routing.
use super::*;

mod next_generation_navigator_mouse_and_keyboard_share_typed_routing;

mod ux_responsive_mouse_regions_keyboard_scroll_and_minimum_are_exact;

mod compact_resource_meters_mouse_geometry_excludes_logs_and_meters;

mod next_generation_mouse_selects_exact_tasks_and_tabs;

mod next_generation_mouse_traps_dialogs_and_resizes_exact_terminal_axis;

mod keymap_function_key_catalog_maps_every_named_route;

mod compatibility_ui_actions_keep_task_shortcuts_authoritative;

mod ux_dashboard_operational_shortcuts_match_the_typed_action_catalog;

mod ux_command_center_routes_to_existing_typed_workspaces_and_terminal_command;

mod enter_activates_contextual_notification;
mod log_workspace_maps_selection_search_filters_and_selected_actions;
mod maps_log_controls;
mod persistent_pane_focus_preserves_global_quit;
mod search_clear_shortcut_maps_to_every_typed_domain;
mod ux_internal_log_keyboard_routes_only_the_separate_diagnostic_authority;
mod ux_logs_keyboard_routes_source_time_bookmarks_and_bounded_export;

mod error_workspace_maps_selection_log_jump_and_source_open;
mod layer_tree_maps_lazy_navigation_hidden_refresh_and_inspector_modes;
mod maps_severity_filter_control;
mod visible_guidance_popup_owns_its_advertised_enter_and_escape_controls;

mod layers_workspace_owns_horizontal_hierarchy_keys_before_pane_focus;

mod navigator_arrows_expand_and_collapse_groups_without_changing_panes;

mod recipes_workspace_maps_search_selection_detail_and_dependencies;
mod ux_list_tree_keyboard_routes_expansion_pages_edges_and_search_without_widget_state;

mod concept_chrome_and_pane_mouse_boundaries_agree_across_resize;

mod selected_menuconfig_uses_inspector_width_and_reports_exact_terminal_cells;

mod terminal_pane_clicks_exclude_navigator_inspector_tabs_and_prefix_rail;
