use super::*;

mod ux_action_catalog_is_unique_complete_and_safe;

mod ux_action_catalog_covers_every_workspace_seed_without_drift;

mod ux_action_catalog_global_metadata_is_searchable_and_menu_ready;
