BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/meta \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/meta-poky \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-microblaze \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-core \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-standalone \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-standalone-sdt \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-bsp \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-vendor \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-virtualization \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-mali400 \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-demos \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-multimedia \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx-tools \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-amd-adaptive-socs/meta-amd-adaptive-socs-core \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-amd-adaptive-socs/meta-amd-adaptive-socs-bsp \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-arm/meta-arm \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-arm/meta-arm-toolchain \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-perl \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-python \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-filesystems \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-gnome \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-multimedia \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-networking \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-webserver \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-xfce \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-initramfs \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openembedded/meta-oe \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx/meta-xilinx-contrib \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-virtualization \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-kria \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-security \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-security/meta-tpm \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-xilinx-tsn \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-petalinux \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-openamp \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-qt5 \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-jupyter \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-ros/meta-ros-common \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-ros/meta-ros2 \
  /home/bspguy-dev/src/yoctui-zcu102-2026.1/sources/poky/../meta-ros/meta-ros2-jazzy \
"
