use super::*;

mod task_identity_unknown_statistics_use_existing_job_progress_without_a_task_row;

mod snapshot_timing_publication_uses_injected_observation_clock;

mod daemon_job_identity_is_unique_across_report_supervisors;

mod tokio_runtime_two_workers_isolate_a_bounded_blocking_poll;

mod ssh_access_origin_uses_the_valid_remote_client_ip;

mod ssh_access_origin_falls_back_to_valid_client_variable;

mod attached_startup_uses_only_daemon_metadata;

mod devwork_editor_atomic_save_preserves_permissions_and_detects_conflicts;

mod devwork_editor_atomic_save_rejects_symlinks_and_paths_outside_workspace;

mod devwork_terminal_detached_plan_preserves_argv_without_shell_evaluation;

mod compatibility_config_query_parses_selected_utility_and_environment_forms;

mod doctor_compatibility_reports_bounded_authority_and_exact_degradation;

mod doctor_compatibility_fails_closed_for_absent_and_malformed_authority;

mod compatibility_workspace_app_cli_routes_local_effect_and_blocks_environment_spawn;

mod compatibility_workspace_app_cli_never_routes_daemon_owned_probe_effects;

mod client_devtool_status_uses_installed_daemon_compatibility_authority;

mod bundled_bridge_is_default_and_explicit_path_remains_an_override;

mod daemon_cli_commands_are_typed_and_destructive_session_kill_is_explicit;

mod binary_product_preserves_one_rust_native_package_without_browser_runtime;

mod pane_split_runtime_updates_client_local_layout_without_daemon_state;

mod reboot_recovery_user_service_can_restart_daemon_after_login_without_root;

mod project_profile_optional_load_and_explicit_generation_are_safe;

mod project_profile_summary_keeps_resolution_explicit;

mod project_profile_rejects_symlinks_invalid_schema_and_unknown_fields;

mod security_daemon_rejects_untrusted_profile_and_shell_command;

mod parses_retention_and_backend_settings;

mod no_build_directory_resolves_to_unconfigured_startup;

mod startup_session_legacy_backend_does_not_override_bridge_default;

mod startup_session_no_color_override_preserves_stored_preference;

mod session_round_trip_preserves_preferences;

mod ux_onboarding_first_run_resume_dismissal_and_validation_are_persistent_and_safe;

mod ux_keymap_persistence_migrates_routes_and_rejects_invalid_atomically;

mod raw_favorite_persistence_round_trips_privately_and_preserves_unrelated_session_state;

mod raw_favorite_persistence_rejects_invalid_atomically_and_retains_stale_templates;

mod raw_favorite_persistence_defaults_legacy_and_rejects_oversized_session;

mod settings_session_overrides_config_but_cli_no_color_remains_authoritative;

mod settings_persistence_preserves_unrelated_session_fields;

mod ux_preferences_migrate_persist_restart_and_reject_future_schema_atomically;

mod layout_restore_round_trips_client_local_pane_tree;

mod settings_persistence_failure_does_not_replace_session_state;

mod normalizes_task_progress_event;

mod parses_cpu_counters_from_proc_stat;

mod telemetry_parsers_accept_linux_values_and_reject_inconsistent_samples;

mod coexistence_output_is_explicitly_advisory_and_read_only;

mod telemetry_sampling_provenance_matches_cli_sampler_and_withholds_first_deltas;

mod telemetry_sampling_derives_only_monotonic_identity_stable_rates;

mod bbmask_assignment_is_single_line_and_shell_quoted;

mod writes_an_explicit_bbmask_assignment_to_local_conf;

mod config_edit_write_replaces_or_appends_atomically_with_permissions_and_crlf;

mod config_edit_write_rejects_tampering_and_leaves_failed_destination_untouched;

mod config_edit_write_refresh_success_replaces_detail_and_failure_preserves_it;

mod config_edit_write_live_snapshot_is_validated_without_mutating_yocto;

mod ctrl_c_is_not_the_regular_cancel_key;

mod search_clear_control_key_decodes_without_becoming_text;

mod terminal_resize_requires_full_redraw;

mod interactive_daemon_logging_keeps_stderr_out_of_terminal_sessions;

mod external_process_redraw_latch_is_edge_triggered;

mod interactive_daemon_reconnect_uses_a_bounded_retry_interval;

mod popup_editor_keys_decode_home_end_and_paste;

mod ux_textarea_bracketed_paste_is_one_typed_bounded_model_action;

mod ux_scroll_real_terminal_page_and_edge_keys_decode_without_aliasing;

mod focus_keys_decode_without_losing_direction;

mod reference_function_keys_decode_without_aliasing;

mod ux_menu_terminal_f10_and_right_click_decode_without_bypassing_typed_routes;

mod dialog_input_routing_prevents_pane_shortcuts_from_leaking;

mod command_palette_input_decodes_search_edit_and_activation_keys;

mod focus_routing_passes_unmatched_global_and_workspace_keys_onward;

mod ux_focus_menu_activation_and_outward_escape_use_the_same_typed_reducer;

mod focus_routing_notifications_consume_only_their_documented_keys;

mod layers_list_enter_right_and_l_open_the_selected_hierarchy;

mod queued_termination_requests_exit_the_tui_loop;

mod config_workspace_terminal_result_preserves_typed_scope_and_history;

mod config_copy_terminal_route_emits_existing_clipboard_effect;

mod config_source_terminal_picker_routes_authoritative_path;

mod config_scope_terminal_picker_emits_recipe_scoped_query;

mod layer_tree_scanner_is_shallow_sorted_and_keeps_hidden_metadata;

mod layer_tree_preview_bounds_large_text_and_rejects_binary;

mod layer_tree_scanner_reports_git_states_without_requiring_git;

mod recipe_bitbake_action_terminal_keys_decode_to_typed_routes;

mod dependency_workspace_terminal_keys_decode_to_typed_routes;

mod recipe_navigation_terminal_keys_and_missing_paths_are_typed;

mod recipe_qa_action_terminal_keys_decode_to_typed_routes;

mod devtool_job_lifecycle_cli_polling_retains_output_during_navigation;

mod devtool_modify_completion_uses_authoritative_source_and_preserves_failures;

mod devtool_publish_update_refreshes_original_identity_and_retains_failure;

mod devtool_publish_finish_refreshes_original_identity_and_retains_job_context;

mod devtool_target_deploy_refreshes_original_identity_and_retains_failures;

mod devtool_target_reset_refreshes_expected_removal_and_retains_failures;

mod signature_workspace_background_operation_reports_success_failure_and_cancellation;

mod pkgdata_workspace_background_operation_binds_current_authority_and_reports_results;

mod images_workspace_background_operation_reports_success_failure_and_cancellation;

mod ux_rootfs_workspace_resolves_exact_artifact_sources_and_updates_model;

mod qemu_workspace_cli_refreshes_capability_and_runs_exact_request_across_navigation;

mod qemu_workspace_cli_reports_nonzero_rejection_forced_cancel_and_loss;

mod wic_device_write_cli_discovers_routes_and_revalidates_before_spawn;

mod wic_workspace_cli_discovers_runs_scans_and_persists_across_navigation;

mod wic_workspace_cli_reports_failure_graceful_and_forced_cancellation;

mod wic_workspace_cli_reports_rejection_and_unexpected_runner_loss;

mod sdk_workflow_cli_inspects_capability_and_correlates_replaceable_scans;

mod sdk_workflow_cli_runs_publish_and_native_with_output_refresh_and_navigation;

mod sdk_workflow_cli_preserves_failure_timeout_cancel_rejection_and_loss;

mod test_workflow_cli_discovers_and_runs_selftest_across_navigation;

mod test_workflow_cli_correlates_managed_bitbake_success_and_cancellation;

mod test_workflow_cli_imports_compares_and_exports_exact_results;

mod security_workflow_cli_discovers_capability_imports_and_preserves_navigation;

mod security_workflow_cli_runs_exact_mapper_refreshes_and_rejects_duplicate_start;

mod security_workflow_cli_cancels_only_the_exact_mapper_session;

mod security_workflow_cli_maps_report_failures_and_replaceable_generations;

mod security_workflow_cli_revalidates_exact_report_provider_and_advisory_opens;

mod security_workflow_cli_reuses_managed_build_coordinator_and_attaches_job;

mod security_workflow_cli_correlates_managed_build_terminal_outcomes;

mod qa_workflow_cli_discovers_capability_imports_reports_and_preserves_navigation;

mod qa_workflow_cli_runs_exact_layer_check_refreshes_and_rejects_duplicate;

mod qa_workflow_cli_cancels_only_exact_native_layer_session;

mod qa_workflow_cli_revalidates_exact_report_provider_source_and_layer_opens;

mod qa_workflow_cli_reuses_managed_build_and_correlates_terminal_outcomes;

mod qa_workflow_cli_preserves_report_terminal_states_and_replaceable_generations;

mod daemon_attach_build_maps_task_stats_into_protocol_and_job_progress;

mod daemon_build_job_updates_preserve_the_requested_targets;

mod qa_workflow_cli_routes_every_workspace_and_modal_key_without_leakage;

mod ux_image_preview_rejection_is_transport_safe_and_keeps_candidate_out_of_binary;

mod ux_terminal_cli_encodes_exact_pty_bytes_including_literal_prefix;

mod daemon_live_event_replay_is_bounded_below_client_poll_capacity;

mod idle_daemon_waits_on_socket_readiness_without_delaying_active_work;

mod normal_render_interval_is_capped_at_ten_hertz;

mod platform_metadata_backend_starts_once_and_rejects_process_mode;

mod function_key_image_navigation_routes_its_local_inventory_effect;

mod daemon_devtool_modify_completion_drives_client_editor_handoff;

mod daemon_client_rootfs_uses_selected_manifest_and_workspace_pkgdata;

mod rootfs_pending_refresh_cancels_without_stranding_new_loading_state;

mod rootfs_completed_metadata_cannot_install_after_authority_loss;

mod support;
use support::*;
