//! Regression tests grouped around snapshot_timing_matches_live_batch_replacement_and_terminal_replay.
use super::*;

mod primary_contract;

mod snapshot_timing_invalid_reversed_and_missing_times_are_unavailable;

mod daemon_attach_build_restores_and_updates_typed_progress_without_replacing_presentation;

mod daemon_attach_uses_top_level_workspace_identity_without_build_event;

mod security_workflow_maps_typed_mapper_events_without_parsing_output;

mod compatibility_recipetool_actions_load_and_unload_from_one_snapshot;

mod compatibility_layers_actions_use_independent_api_and_command_records;

mod compatibility_pkgdata_actions_distinguish_artifact_command_and_unknown_state;

mod raw_selector_app_projection_replaces_workspace_and_target_inventories;

mod raw_selector_app_projection_rejects_stale_tasks_but_keeps_valid_manual_entry;

mod raw_argv_app_mapping_uses_shared_editor_commands_and_explicit_validation;

mod raw_argv_app_validation_returns_native_elements_and_replaces_stale_results;

mod raw_search_app_maps_browser_history_and_favorite_input_mechanically;
