//! Regression tests grouped around task_identity_statistics_decode_without_recipe_or_task_inference.
use super::*;

mod task_identity_statistics_decode;

mod devtool_metadata_fake_process_reports_workspace_and_dirty_git_state;

mod devtool_job_spec_builds_exact_shell_free_arguments_for_every_operation;

mod devtool_job_spec_rejects_invalid_operations_before_process_construction;

mod devtool_publish_update_uses_exact_shell_free_arguments;

mod devtool_publish_finish_uses_exact_shell_free_arguments;

mod devtool_publish_finish_preserves_native_destination_bytes;

mod devtool_target_deploy_validates_before_exact_shell_free_arguments;

mod devtool_target_reset_uses_exact_shell_free_arguments;

mod devtool_job_spec_preserves_non_utf8_finish_destination;

mod devtool_job_runner_streams_bounded_stdout_stderr_and_invalid_utf8;

mod devtool_job_runner_rejects_duplicate_missing_and_failed_processes;

mod devtool_job_runner_acknowledges_and_escalates_cancellation;

mod devtool_job_runner_reports_unexpected_event_channel_loss;

mod devtool_metadata_distinguishes_missing_tool_and_workspace_directory;

mod devtool_metadata_rejects_malformed_external_records;

mod devtool_metadata_ignores_bounded_bitbake_diagnostics;

mod devtool_status_cancellation_kills_the_probe;

mod ansi_and_severity;
mod typed_event_preserves_unknown_progress_and_ignores_future_events;

mod dependency_graph_typed_event_converts_nodes_edges_and_limitations;

mod config_metadata_converts_scope_unexpanded_value_and_operations;
mod invalid_utf8_output_is_preserved_lossily;
mod live_tasks_preserves_queue_statistics_and_task_details;
mod recipe_metadata_converts_typed_statuses_and_paths;
mod typed_event_workspace_converts_wire_paths_and_metadata;

mod oversized_process_line_is_truncated_and_stream_continues;

mod process_backend_collects_both_output_streams;

mod dependency_graph_dot_parser_normalizes_task_build_cycles_and_bounds;
