[package]
name = "yoctui-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Application input and effect mapping for Yoctui"
publish = ["crates-io"]
[dependencies]
yoctui-bitbake = { version = "0.1.39", path = "../yoctui-bitbake" }
yoctui-model = { version = "0.1.39", path = "../yoctui-model" }
yoctui-protocol = { version = "0.1.39", path = "../yoctui-protocol" }
thiserror.workspace = true
