[package]
name = "yoctui-app"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
yoctui-bitbake = { version = "0.1.0", path = "../yoctui-bitbake" }
yoctui-model = { version = "0.1.0", path = "../yoctui-model" }
yoctui-protocol = { version = "0.1.0", path = "../yoctui-protocol" }
thiserror.workspace = true
