//! Regression tests grouped around qa_workflow_renders_both_views_findings_inspector_themes_and_breakpoints.

include!("01_qa_workflow_renders_both_views_findings_inspector_themes_and_breakpoints.rs");

include!("02_maintenance_workflow_dialogs_render_exact_safety_meaning_at_80x24.rs");

include!("03_raw_form_routes_manual_selector_and_argv_edits_to_exact_preview.rs");
