[package]
name = "yoctui-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
publish = ["crates-io"]

description = "Shared utility functions for Yoctui"

[dependencies]
dirs = "7"
libc.workspace = true
