[package]
name = "yoctui-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Ratatui rendering layer for Yoctui"
publish = ["crates-io"]
[dependencies]
yoctui-app = { version = "0.1.13", path = "../yoctui-app" }
yoctui-model = { version = "0.1.13", path = "../yoctui-model" }
ratatui.workspace = true
throbber-widgets-tui.workspace = true
tui-piechart.workspace = true
tui-term.workspace = true
